Repository Artea-Station/Artea-Station-Server, pull requests merged in 2023-05, with the labels that each got.

#172 Remove Removed Antags From TGUI
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/abductor.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/blob.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/blobinfection.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/clownoperative.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/cultist.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/headrevolutionary.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/heretic.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/hereticsmuggler.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/loneoperative.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/obsessed.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/operative.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/operativemidround.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/provocateur.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/revenant.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/sentientdisease.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/spacedragon.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/traitor.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/wizard.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/wizardmidround.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/xenomorph.ts
Labels: UI, Fix

#163 The Soundening!
  code/__DEFINES/sound.dm
  code/datums/components/crafting/recipes.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/machinery/PDApainter.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/bank_machine.dm
  code/game/machinery/buttons.dm
  code/game/machinery/civilian_bounties.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/computer/prisoner/_prisoner.dm
  code/game/machinery/newscaster/newscaster_machine.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/machinery/slotmachine.dm
  code/game/machinery/spaceheater.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/sound.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/portable/pump.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/modular_computers/computers/item/computer.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/modular_computers/computers/item/pda.dm
  code/modules/modular_computers/computers/machinery/modular_computer.dm
  code/modules/paperwork/fax.dm
  code/modules/power/apc/apc_power_proc.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/rdconsole.dm
  code/modules/vehicles/mecha/mech_fabricator.dm
  code/modules/wiremod/core/usb_cable.dm
  sound/effects/woodcutting.ogg
  sound/machines/airpumpidle.ogg
  sound/machines/airpumpidle1.ogg
  sound/machines/airpumpidle2.ogg
  sound/machines/airpumpidle3.ogg
  sound/machines/airpumpidle4.ogg
  sound/machines/airpumpidle5.ogg
  sound/machines/airpumpshutdown.ogg
  sound/machines/airpumpstart.ogg
  sound/machines/breaker_off.ogg
  sound/machines/breaker_on.ogg
  sound/machines/id_eject.ogg
  sound/machines/id_insert.ogg
  sound/machines/keypress1.ogg
  sound/machines/keypress2.ogg
  sound/machines/keypress3.ogg
  sound/machines/keypress4.ogg
  sound/machines/keypress5.ogg
  sound/machines/pda_click.ogg
  sound/machines/pen_remove.ogg
  sound/machines/switch1.ogg
  sound/machines/switch2.ogg
  sound/machines/switch3.ogg
Labels: Sounds

#176 [PORT] Emp's no longer stun but disable robotic limbs now
  code/__DEFINES/traits.dm
  code/modules/client/client_colour.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/robot_bodyparts.dm
Labels: Balance, Port

#177 [Port] Ports the Bunny suit from Skyrat and adds it to the autodrobe
  code/modules/clothing/under/costume.dm
  code/modules/vending/autodrobe.dm
  icons/mob/clothing/under/costume.dmi
  icons/obj/clothing/under/costume.dmi
Labels: Sprites

#179 Window de-construction QOL
  code/game/objects/structures/window.dm
Labels: Quality of Life

#180 [Port] Organizes the autodrobe better
  code/modules/vending/autodrobe.dm
Labels: Quality of Life

#178 Removes Metastation
  _maps/_basemap.dm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/metastation.json
  code/datums/map_config.dm
  code/modules/map_content/metastation_define.dm
  config/maps.txt
  tgstation.dme
Labels: Config Update, Mapping, Removal

#182 [Port] Adds damaged window and broken machine helpers
  code/modules/mapfluff/ruins/spaceruin_code/oldstation.dm
  code/modules/mapping/mapping_helpers.dm
  icons/effects/mapping_helpers.dmi
Labels: Sprites

#184 funny double text removal on supply pod beacons
  code/modules/cargo/supplypod_beacon.dm
Labels: Removal

#187 Shift Fax Machines to Look Correct On Tables
  code/modules/paperwork/fax.dm
Labels: Quality of Life, My Opinion is Correct

#186 Adds Wired and Wired+Anchored Machine Frame Subtypes
  code/game/machinery/constructable_frame.dm
Labels: Quality of Life

#185 Make Suit Storage Unit Use Industrial Sprites
  code/game/machinery/suit_storage_unit.dm
Labels: Sprites, My Opinion is Correct

#181 Floor Sprites Tweak
  icons/turf/floors.dmi
Labels: Quality of Life, Sprites

#190 [PORT] PDA's now have mapping Icons
  icons/obj/modular_pda.dmi
Labels: Sprites, Port, Fix

#189 Adds Pathfinders to Kilo station (Rest in piss science)
  _maps/map_files/KiloStation/KiloStation.dmm
  code/game/area/areas/station.dm
Labels: Mapping, Removal, Sprites

#200 Moved Erp prefs down to the bottom of the list in content selection
  code/modules/client/preferences/content.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/content.tsx
Labels: UI

#198 [FUCK] Fixes pathfinders department not loading properly during init (This is a fix that only applies to me for some reason, so grammer formatting lol)
  code/game/area/areas/station.dm
Labels: Grammar and Formatting, Fix

#199 Fixes some mapping issues we had with pathfinders along with other pathfinder related stuff
  _maps/map_files/KiloStation/KiloStation.dmm
  code/__DEFINES/access.dm
  code/controllers/subsystem/id_access.dm
  code/game/area/areas/station.dm
  code/game/objects/effects/landmarks.dm
  code/modules/pathfinders/access_helpers.dm
  code/modules/pathfinders/lockers.dm
  code/modules/pathfinders/pathfinder_lead_job.dm
  code/modules/pathfinders/radio.dm
  code/modules/pathfinders/vendors.dm
  icons/mob/landmarks.dmi
Labels: Mapping, Sprites, Fix

#202 Fix Pathfinder Med Radios, Fix Lead Pathfinder's Outfit Name
  code/modules/pathfinders/pathfinder_job.dm
  code/modules/pathfinders/pathfinder_lead_job.dm
  code/modules/pathfinders/radio.dm
Labels: Fix

#204 [PORT] Adds a message to the autokick for when people send too many inputs.
  code/modules/keybindings/bindings_client.dm
Labels: Port

#211 Fixed a tiny mapping error on Kilo
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Fix

#215 [PORT] Ports the Engi dufflebag sprite from Beestation.
  icons/mob/clothing/back.dmi
  icons/obj/storage/storage.dmi
Labels: Sprites, Port

#210 [PORT] Animates several emotes.
  code/modules/mob/living/emote.dm
Labels: Port

#218 [PORT] Re-sprite for MODsuit buttons. [MDB IGNORE]
  code/modules/mod/mod_actions.dm
  code/modules/mod/modules/module_pathfinder.dm
  icons/mob/actions/actions_mod.dmi
  icons/mob/actions/backgrounds.dmi
Labels: Sprites, Port

#214 Fix Pathfinder Access
  code/__DEFINES/access.dm
  code/controllers/subsystem/id_access.dm
  code/modules/pathfinders/pathfinder_job.dm
  code/modules/pathfinders/pathfinder_lead_job.dm
Labels: Fix

#192 Makes Ballistic Projectiles Significantly Damage Walls
  code/game/turfs/closed/walls.dm
  code/modules/projectiles/projectile.dm
Labels: Balance

#203 Fix Inspection Menu Not Showing!
  code/modules/tgui/states/physical.dm
Labels: Stale, Fix

#193 [AAAAA] Pathfinders Shuttle!
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/shuttles/pathfinders_ghetto.dmm
  code/datums/shuttles.dm
  code/game/area/areas/overmap_shuttles.dm
  code/modules/shuttle/common_docks.dm
Labels: Mapping, Stale

#212 Added sounds to Security jackboots.
  code/modules/clothing/shoes/boots.dm
Labels: Sounds
