Repository Artea-Station/Artea-Station-Server, pull requests merged in 2023-12, with the labels that each got.

#414 Bearcat Mapping tweaks
  _maps/map_files/Bearcat/Bearcat.dmm
Labels: Feature, Mapping

#413 Transporter pad fix
  code/modules/overmap/transporter.dm
Labels: Feature

#415 [Port] Mech transport ruin update
  _maps/RandomRuins/SpaceRuins/mechtransport.dmm
  code/game/turfs/open/floor/catwalk_plating.dm
  code/game/turfs/open/floor/iron_floor.dm
Labels: Mapping, Quality of Life

#412 Makes the produce order console board printable
  code/modules/research/designs/comp_board_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#429 Removes Psychologist (Schizo freedom edition)
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/jobs.dm
  code/datums/id_trim/jobs.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/effects/landmarks.dm
  code/modules/antagonists/traitor/objectives/kidnapping.dm
  code/modules/jobs/job_types/psychologist.dm
  code/modules/library/skill_learning/job_skillchips/psychologist.dm
  tgstation.dme
Labels: Mapping, Removal

#391 Locker Resprite!
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  icons/obj/storage/closet.dmi
Labels: Feature, Sprites

#417 Fix Signing Playing Say Sounds
  code/modules/mob/living/living_say.dm
Labels: Fix

#410 Gives MODsuits Hardsuit armor values (#403 fix)
  code/modules/clothing/spacesuits/hardsuit.dm
  code/modules/mod/mod_theme.dm
Labels: Balance

#411 Door, Computer, Windoor, Booze-O-Mat, and Wood Floor Resprite!
  code/game/machinery/computer/_computer.dm
  code/modules/modular_computers/computers/machinery/modular_computer.dm
  code/modules/modular_computers/computers/machinery/modular_console.dm
  icons/obj/computer.dmi
  icons/obj/doors/airlocks/station/airlock.dmi
  icons/obj/doors/airlocks/station/airlock_color.dmi
  icons/obj/doors/airlocks/station/airlock_stripe.dmi
  icons/obj/doors/airlocks/station/glass_overlays.dmi
  icons/obj/doors/airlocks/station/note_overlays.dmi
  icons/obj/doors/airlocks/station/overlays.dmi
  icons/obj/doors/windoor.dmi
  icons/obj/modular_console.dmi
  icons/obj/vending.dmi
  icons/turf/floors.dmi
Labels: Feature, Sprites, Fix

#416 Fix Job Preferences
  code/controllers/subsystem/job.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences/middleware/jobs.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/JobsPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/data.ts
Labels: UI, Fix

#440 Fix SSday_night Showing Init Warnings
  code/controllers/subsystem/day_night.dm
Labels: Fix

#441 Fix Default World Name Being Wrong
  code/world.dm
Labels: Fix

#439 [TGChat] [Port] Change Backend Database, Some Minor Tweaks
  tgui/packages/common/storage.js
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/settings/constants.js
  tgui/packages/tgui-panel/settings/middleware.js
  tgui/packages/tgui-panel/settings/reducer.js
  tgui/packages/tgui-panel/themes.js
Labels: Quality of Life, UI, Port

#432 LOOC "Are You Sure" No Longer Trips For Common Smileys
  code/modules/client/verbs/looc.dm
Labels: Quality of Life

#431 Add Synthmeat to The Biogen, Adjust Monkey Cube Print Cost
  code/modules/research/designs/biogenerator_designs.dm
Labels: Balance, Quality of Life

#443 More bearcat mapping tweaks
  _maps/map_files/Bearcat/Bearcat.dmm
Labels: Mapping

#447 Fix Built Sec Peacekeeper MODs Not Starting With Their Unique Stuff
  code/modules/mod/mod_theme.dm
  code/modules/mod/mod_types.dm
Labels: Fix

#445 Improves Overmap significantly
  code/__DEFINES/overmap.dm
Labels: Quality of Life

#442 [PORT] Swipes Cyborg Chargers Working on Synths From Bubber
  code/modules/surgery/organs/stomach/stomach_synth.dm
Labels: Feature, Port

#449 New Space Background!
  icons/effects/parallax.dmi
Labels: Feature, Sprites

#453 [PORT] Swipes Most TG CI Changes From The Last Year [MDB IGNORE]
  .github/max_required_byond_client.txt
  .github/workflows/ci_suite.yml
  .github/workflows/docker_publish.yml.disabled
  .github/workflows/generate_documentation.yml.disabled
  .github/workflows/run_integration_tests.yml
  .github/workflows/show_screenshot_test_results.yml
  _maps/RandomRuins/IceRuins/icemoon_surface_bughabitat.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/hellfactory.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/RandomZLevels/snowdin.dmm
  _maps/map_files/CTF/cruiser.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/shuttles/infiltrator_advanced.dmm
  code/modules/food_and_drinks/machinery/coffeemaker.dm
  code/modules/unit_tests/_unit_tests.dm
  dependencies.sh
  tools/ci/annotate_dm.py
  tools/ci/annotate_dm.sh
  tools/ci/check_grep.sh
  tools/maplint/README.md
  tools/maplint/lints/apc_pixel_shifts.yml
  tools/maplint/lints/area_varedits.yml
  tools/maplint/lints/base_turf.yml
  tools/maplint/lints/cable_varedits.yml
  tools/maplint/lints/conveyor_cardinal_inversion.yml
  tools/maplint/lints/custom_icon_helper.yml
  tools/maplint/lints/docking_port_varedits.yml
  tools/maplint/lints/door_name_capitalization.yml
  tools/maplint/lints/grille_stacking.yml
  tools/maplint/lints/identical_barricades.yml
  tools/maplint/lints/identical_pipes.yml
  tools/maplint/lints/merge_conflict_marker.yml
  tools/maplint/lints/multiple_airlocks.yml
  tools/maplint/lints/multiple_area.yml
  tools/maplint/lints/multiple_cables.yml
  tools/maplint/lints/multiple_chairs.yml
  tools/maplint/lints/multiple_closets.yml
  tools/maplint/lints/multiple_firelocks.yml
  tools/maplint/lints/multiple_girders.yml
  tools/maplint/lints/multiple_grilles.yml
  tools/maplint/lints/multiple_lattice.yml
  tools/maplint/lints/multiple_stairs.yml
  tools/maplint/lints/multiple_tables.yml
  tools/maplint/lints/multiple_turf.yml
  tools/maplint/lints/pixel_varedits.yml
  tools/maplint/lints/stairs_with_genturf.yml
  tools/maplint/lints/wall_stacking.yml
  tools/maplint/source/__init__.py
  tools/maplint/source/__main__.py
  tools/maplint/source/common.py
  tools/maplint/source/dmm.py
  tools/maplint/source/error.py
  tools/maplint/source/lint.py
  tools/requirements.txt
  tools/ticked_file_enforcement/schemas/tgstation_dme.json
  tools/ticked_file_enforcement/schemas/unit_tests.json
  tools/ticked_file_enforcement/ticked_file_enforcement.py
  tools/validate_dme.py
Labels: Continuous Integration, Mapping, Tools, Port, Repository

#433 Major Resprite Overhaul
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/shuttles/emergency_cruise.dmm
  code/__DEFINES/apc_defines.dm
  code/game/machinery/computer/_computer.dm
  code/modules/modular_computers/computers/machinery/modular_console.dm
  code/modules/power/apc/apc_main.dm
  code/modules/power/apc/apc_mapping.dm
  code/modules/vending/_vending.dm
  code/modules/vending/cigarette.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/coffee.dm
  code/modules/vending/cola.dm
  code/modules/vending/drinnerware.dm
  code/modules/vending/engivend.dm
  code/modules/vending/medical.dm
  code/modules/vending/megaseed.dm
  code/modules/vending/nutrimax.dm
  code/modules/vending/security.dm
  code/modules/vending/snack.dm
  code/modules/vending/sustenance.dm
  icons/obj/atmospherics/components/unary_devices.dmi
  icons/obj/chairs.dmi
  icons/obj/computer.dmi
  icons/obj/medical/rollerbed.dmi
  icons/obj/medical/surgery_table.dmi
  icons/obj/medical/surgery_tools.dmi
  icons/obj/modular_console.dmi
  icons/obj/objects.dmi
  icons/obj/power.dmi
  icons/obj/stationobjs.dmi
  icons/obj/storage/closet.dmi
  icons/obj/storage/crates.dmi
  icons/obj/structures.dmi
  icons/obj/vending.dmi
  icons/obj/watercloset.dmi
  icons/turf/floors.dmi
  tools/UpdatePaths/Artea/433_remove_red_cola.txt
Labels: Feature, Mapping, Removal, Sprites, Tools

#446 [Bearcat] Partial Engineering Remap
  _maps/map_files/Bearcat/Bearcat.dmm
Labels: Mapping, Quality of Life, Fix

#457 Fix The SM Having No Roof
  _maps/map_files/Bearcat/Bearcat.dmm
Labels: OH SHIT, Mapping, Fix

#444 Returns MDs and CMOs to Starting With Their Normal Uniforms
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_moth.png
Labels: Quality of Life

#461 Makes Screenshot Test Bad-Screenshots Prefix Images
  tools/screenshot-test-comparison/index.js
Labels: Tools

#463 Walls Windows and Widgets
  icons/obj/atmospherics/atmos.dmi
  icons/obj/chairs.dmi
  icons/obj/library.dmi
  icons/obj/lighting.dmi
  icons/obj/power.dmi
  icons/obj/smooth_structures/catwalk.dmi
  icons/obj/smooth_structures/catwalk.png
  icons/obj/smooth_structures/lattice.dmi
  icons/obj/smooth_structures/lattice.png
  icons/obj/smooth_structures/reinforced_table.dmi
  icons/obj/smooth_structures/reinforced_table.png
  icons/obj/smooth_structures/table.dmi
  icons/obj/smooth_structures/table.png
  icons/obj/smooth_structures/window.dmi
  icons/obj/smooth_structures/window.png
  icons/obj/smooth_structures/window_reinforced.png
  icons/obj/smooth_structures/wood_table.dmi
  icons/obj/smooth_structures/wood_table.png
  icons/obj/stationobjs.dmi
  icons/obj/structures/elevator_control.dmi
  icons/obj/watercloset.dmi
  icons/turf/floors.dmi
  icons/turf/walls/solid_wall.dmi
  icons/turf/walls/solid_wall.png
  icons/turf/walls/solid_wall_reinforced.dmi
  icons/turf/walls/solid_wall_reinforced.png
  icons/turf/walls/solid_wall_reinforced_shine.dmi
  icons/turf/walls/solid_wall_reinforced_shine.png
  icons/turf/walls/solid_wall_shine.dmi
  icons/turf/walls/solid_wall_shine.png
  icons/turf/walls/wall_stripe.dmi
  icons/turf/walls/wall_stripe.png
  icons/turf/walls/wall_stripe_shine.dmi
  icons/turf/walls/wall_stripe_shine.png
Labels: Sprites, Repository

#467 Nosha > Ryoshi
  code/__DEFINES/manufacturers.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/pai/card.dm
  code/modules/research/machinery/_production.dm
  code/modules/surgery/organs/brain_synth.dm
Labels: Grammar and Formatting

#464 New Railings
  code/game/objects/structures/railings.dm
  icons/obj/fluff.dmi
  icons/obj/structures/railing.dmi
Labels: Feature, Sprites

#459 Lints For Multiple of The Same Machine, Also Fixes Lint Type
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/waystation.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  tools/maplint/lints/multiple_machinery.yml
  tools/maplint/source/lint.py
Labels: Mapping, Tools

#469 OH MY GOD STOP CHANGING
  .vscode/settings.json
Labels: Repository, ???

#471 Minor mapping fix for bearcat
  _maps/map_files/Bearcat/Bearcat.dmm
Labels: Mapping, Fix

#477 Mini Soundening (overmap edition)
  code/modules/overmap/overmap_lock.dm
  code/modules/overmap/overmap_shuttle.dm
Labels: Quality of Life

#475 Fix Trade Runs Not Completing
  code/modules/trading/delivery_runs/_delivery_run.dm
Labels: Fix

#389 Space Audio Stuff!
  code/game/sound.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human_say.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/life.dm
  sound/voice/breathing.ogg
Labels: Feature, Sounds

#375 [PORT] Stop, Drop, Roll QoL Improvements!
  code/_onclick/hud/alert.dm
  code/datums/status_effects/buffs/stop_drop_roll.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  tgstation.dme
Labels: Fresh Like Cheese, Quality of Life, Port

#460 [Port] Particles!
  code/__DEFINES/generators.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/particles.dm
  code/__DEFINES/vv.dm
  code/__HELPERS/generators.dm
  code/datums/components/smooth_tunes.dm
  code/datums/status_effects/debuffs/choke.dm
  code/datums/status_effects/debuffs/fire_stacks.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/particle_holder.dm
  code/game/objects/effects/particles/fire.dm
  code/game/objects/effects/particles/smoke.dm
  code/game/objects/effects/particles/stink.dm
  code/game/objects/effects/particles/water.dm
  code/game/objects/structures/bonfire.dm
  code/modules/admin/holder2.dm
  code/modules/admin/view_variables/particle_editor.dm
  code/modules/asset_cache/assets/particle_editor.dm
  code/modules/client/client_procs.dm
  code/modules/food_and_drinks/plate.dm
  code/modules/religion/festival/note_particles.dm
  icons/effects/particles/generic.dmi
  icons/ui_icons/particle_editor/box_gen.png
  icons/ui_icons/particle_editor/circle_gen.png
  icons/ui_icons/particle_editor/cube_gen.png
  icons/ui_icons/particle_editor/linear_rand.png
  icons/ui_icons/particle_editor/motion.png
  icons/ui_icons/particle_editor/normal_rand.png
  icons/ui_icons/particle_editor/num_gen.png
  icons/ui_icons/particle_editor/sphere_gen.png
  icons/ui_icons/particle_editor/square_gen.png
  icons/ui_icons/particle_editor/square_rand.png
  icons/ui_icons/particle_editor/uniform_rand.png
  icons/ui_icons/particle_editor/vector_gen.png
  tgstation.dme
  tgui/packages/tgui/interfaces/ParticleEdit/EntriesBasic.tsx
  tgui/packages/tgui/interfaces/ParticleEdit/EntriesGenerators.tsx
  tgui/packages/tgui/interfaces/ParticleEdit/Generators.tsx
  tgui/packages/tgui/interfaces/ParticleEdit/Tutorial.tsx
  tgui/packages/tgui/interfaces/ParticleEdit/data.ts
  tgui/packages/tgui/interfaces/ParticleEdit/helpers.ts
  tgui/packages/tgui/interfaces/ParticleEdit/index.tsx
Labels: Feature, Sprites, UI

#452 [PORT] Swipes Some Firelock Fixes From TG, Makes Fulltile Windows Update Firelocks
  code/game/machinery/doors/firedoor.dm
  code/game/objects/structures/window.dm
  code/game/turfs/change_turf.dm
Labels: Quality of Life, Port

#455 [Port] Ports movable physics from Novus
  code/__DEFINES/movable_physics.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/vv.dm
  code/_globalvars/bitfields.dm
  code/controllers/subsystem/processing/movable_physics.dm
  code/datums/components/movable_physics.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/modules/admin/view_variables/modify_variables.dm
  code/modules/admin/view_variables/movable_physics_tester.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/projectiles/boxes_magazines/_box_magazine.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/ballistic/toy.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/recharge.dm
  code/modules/projectiles/guns/magic.dm
  code/modules/projectiles/guns/special/chem_gun.dm
  code/modules/projectiles/guns/special/syringe_gun.dm
  html/changelogs/AutoChangeLog-pr-375.yml
  html/changelogs/AutoChangeLog-pr-389.yml
  html/changelogs/AutoChangeLog-pr-460.yml
  tgstation.dme
  tgui/packages/tgui/interfaces/MovablePhysicsTester.tsx
Labels: Feature, UI

#479 Allow Numbers in Any Name
  code/modules/client/preferences/names.dm
Labels: Fix

#482 Removes Runed metal from Overmap loot table
  code/game/objects/effects/spawners/random/materials.dm
Labels: Removal

#481 Adds Orange markings
  _maps/map_files/Bearcat/Bearcat.dmm
  code/game/objects/effects/decals/turfdecal/markings.dm
  icons/turf/decals.dmi
Labels: Feature, Mapping, Sprites

#484 Bearcat Asteroid removal
  _maps/map_files/Bearcat/Bearcat.dmm
Labels: Mapping, Removal

#483 Fixes Lizard Customization At Long Last, Cleans Up Some Of My Prefs Shitcode
  code/modules/client/preferences/_preference.dm
  code/modules/client/preferences/species_features/_mutant.dm
  code/modules/client/preferences/species_features/human.dm
  code/modules/client/preferences/species_features/lizard.dm
  code/modules/client/preferences/species_features/pod.dm
  code/modules/client/preferences/species_features/synth.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories/mutant/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/mutant/frills.dm
  code/modules/mob/dead/new_player/sprite_accessories/mutant/horns.dm
  code/modules/mob/dead/new_player/sprite_accessories/mutant/snouts.dm
  code/modules/mob/dead/new_player/sprite_accessories/mutant/spines.dm
  code/modules/mob/dead/new_player/sprite_accessories/mutant/tails.dm
  code/modules/mob/dead/new_player/synth_sprite_accessories.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/surgery/organs/external/tails.dm
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_lizard.png
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_lizard_ashwalker.png
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_lizard_silverscale.png
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
Labels: UI, Fix

#488 Adds a Unit Test for Turf Sound Sanity
  code/modules/overmap/planets/planet_types/barren_planet.dm
  code/modules/overmap/planets/planet_types/chlorine_planet.dm
  code/modules/overmap/planets/planet_types/shrouded_planet.dm
  code/modules/overmap/planets/planetary_objects.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/turf_sound.dm
Labels: Fix

#489 Space law rename + Lawyer removal
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/tramstation/modular_pieces/maintenance_upperbridgeright_attachment_a_1.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/jobs.dm
  code/controllers/subsystem/id_access.dm
  code/datums/id_trim/jobs.dm
  code/game/machinery/computer/crew.dm
  code/game/machinery/computer/prisoner/management.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/manuals.dm
  code/game/objects/structures/signs/signs_departments.dm
  code/modules/antagonists/traitor/objectives/kidnapping.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/internal_affairs_agent.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/mapping/access_helpers.dm
  code/modules/mining/ores_coins.dm
  code/modules/modular_computers/computers/item/role_tablet_presets.dm
  html/changelogs/archive/2020-04.yml
  icons/mob/landmarks.dmi
  strings/cas_black.txt
  tgstation.dme
Labels: Mapping, Refactor, Removal, Sprites

#493 Fix Border Firelocks Not Stopping Movement Out Of Their Turf
  code/game/machinery/doors/firedoor.dm
Labels: Fix

#492 Fix Box Open Sound Being Too Loud
  code/game/objects/items/storage/boxes/_boxes.dm
  sound/items/storage/card_box.ogg
Labels: Sounds, Fix

#491 Fix *Me Emotes Not Getting Formatted
  code/datums/emotes.dm
Labels: Fix

#495 Fix Jumpy Lobby Cam
  code/controllers/subsystem/lobby_eye_ss.dm
  code/modules/client/preferences/lobby_cam.dm
Labels: Fix

#494 Closets Mk3
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  icons/obj/storage/closet.dmi
Labels: Feature, Sprites

#490 Prefs Deshittening Part 4
  code/datums/matchmaking_panel.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences/assets.dm
  code/modules/client/preferences/migrations/tgui_prefs_migration.dm
  code/modules/client/preferences/security_department.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species_types/synthetic.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/AppearancePage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/Base.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/ClothingPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/FoodPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/IndexPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/LoadoutPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
Labels: Quality of Life, UI

#506 oh shit something broke and byond is angry
  code/game/objects/items/extinguisher.dm
Labels: Fix

#507 Fix A Windoor and Booze-O-Mat Sprite
  icons/obj/doors/windoor.dmi
  icons/obj/vending.dmi
Labels: Sprites, Fix
