Repository Artea-Station/Artea-Station-Server, pull requests merged in 2023-03, with the labels that each got.

#58 Lobby Camera???
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/lobby_eye_ss.dm
  code/modules/client/preferences/lobby_cam.dm
  config/config.txt
  icons/lobby_cam/black_screen.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/lobby_eye.tsx
Labels: Config Update, Sprites, Test Merge Candidate, UI, Fix, Test Merged

#61 Fixes girder runtime.
  code/game/objects/structures/girders.dm
Labels: Fix

#60 [PORT] Changes Spastic to muscle spasms.
  code/datums/mutations/body.dm
  code/game/objects/items/dna_injector.dm
Labels: Port

#63 Fixes Split personality Ghosting its owner if cured ina wrong moment
  code/datums/brain_damage/split_personality.dm
Labels: Fix

#68 Low wall painting fix
  code/game/objects/structures/low_wall.dm
Labels: Fix

#70 Disables the tab hotkey for switching say mode
  tgui/packages/tgui-say/handlers/keyDown.tsx
Labels: UI

#73 [PORT] Ports new material and ore sprites from TG.
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/runed_metal.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/telecrystal.dm
  icons/obj/ore.dmi
  icons/obj/stack_objects.dmi
  icons/obj/telescience.dmi
Labels: Sprites, Port

#72 New TGUI for the ORM
  code/modules/mining/machine_redemption.dm
  tgui/packages/tgui/interfaces/OreRedemptionMachine.js
Labels: UI

#71 [VeggieTales] New veggie and fruit sprites!
  icons/obj/hydroponics/harvest.dmi
Labels: Sprites

#62 Makes Lighting More Moody (Dim+Warmer) And Dynamically Generate Night Shift Values
  code/modules/power/lighting/light.dm
  code/modules/power/lighting/light_mapping_helpers.dm
Labels: Code Improvement, Quality of Life

#79 [OH NO] Fixes Centcom is_station_level Checks
  code/game/turfs/closed/walls.dm
Labels: OH SHIT, Fix

#76 Makes Proper borg ID display on the ORM
  code/modules/mining/machine_redemption.dm
  tgui/packages/tgui/interfaces/OreRedemptionMachine.js
Labels: UI

#82 Modsuit doesn't QDEL on clickdrag while worn anymore
  code/modules/mod/mod_control.dm
Labels: Fix

#74 Gives techfabs soul and a baller look.
  code/modules/research/machinery/departmental_techfab.dm
  code/modules/research/machinery/techfab.dm
  icons/obj/machines/research.dmi
Labels: Sprites

#75 [INTENSE SUFFERING] [PORT] TGUI Techfabs, but Without The Lost Features!
  code/__DEFINES/exosuit_fab.dm
  code/__DEFINES/research/research_categories.dm
  code/datums/components/material_container.dm
  code/game/machinery/autolathe.dm
  code/modules/mining/lavaland/tendril_loot.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/research/designs.dm
  code/modules/research/designs/AI_module_designs.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/bluespace_designs.dm
  code/modules/research/designs/comp_board_designs.dm
  code/modules/research/designs/computer_part_designs.dm
  code/modules/research/designs/electronics_designs.dm
  code/modules/research/designs/experisci_designs.dm
  code/modules/research/designs/limbgrower_designs.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/designs/mecha_designs.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/designs/mining_designs.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/designs/power_designs.dm
  code/modules/research/designs/smelting_designs.dm
  code/modules/research/designs/stock_parts_designs.dm
  code/modules/research/designs/telecomms_designs.dm
  code/modules/research/designs/tool_designs.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/designs/wiremod_designs.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/techweb/_techweb.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/vehicles/mecha/mech_fabricator.dm
  code/modules/wiremod/core/component_printer.dm
  tgui/packages/tgui/interfaces/Autolathe.js
  tgui/packages/tgui/interfaces/Autolathe.tsx
  tgui/packages/tgui/interfaces/ComponentPrinter.tsx
  tgui/packages/tgui/interfaces/ExosuitFabricator.js
  tgui/packages/tgui/interfaces/ExosuitFabricator.tsx
  tgui/packages/tgui/interfaces/Fabrication/CategoryTabs.tsx
  tgui/packages/tgui/interfaces/Fabrication/DesignBrowser.tsx
  tgui/packages/tgui/interfaces/Fabrication/DesignCategoryTabs.tsx
  tgui/packages/tgui/interfaces/Fabrication/DesignCostList.tsx
  tgui/packages/tgui/interfaces/Fabrication/MaterialAccessBar.tsx
  tgui/packages/tgui/interfaces/Fabrication/MaterialCostSequence.tsx
  tgui/packages/tgui/interfaces/Fabrication/MaterialIcon.tsx
  tgui/packages/tgui/interfaces/Fabrication/SearchBar.tsx
  tgui/packages/tgui/interfaces/Fabrication/Types.ts
  tgui/packages/tgui/interfaces/Fabricator.tsx
  tgui/packages/tgui/interfaces/common/Materials.tsx
  tgui/packages/tgui/styles/interfaces/Fabricator.scss
Labels: Code Improvement, Quality of Life, UI, Port, Fix

#87 [PORT] Ports Bay Air alarms
  code/modules/atmospherics/machinery/airalarm.dm
  icons/obj/airalarm.dmi
  icons/obj/monitors.dmi
  icons/obj/wallframe.dmi
Labels: Sprites, Port

#80 [PORT] Baylights
  code/__DEFINES/directional.dm
  code/modules/power/lighting/light_mapping_helpers.dm
Labels: Feature, Quality of Life, Port

#85 Removes Virologist Job and Disables Random Virus Outbreaks
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/jobs.dm
  code/datums/id_trim/jobs.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/toys.dm
  code/modules/antagonists/traitor/objectives/destroy_heirloom.dm
  code/modules/antagonists/traitor/objectives/kidnapping.dm
  code/modules/antagonists/traitor/objectives/sleeper_protocol.dm
  code/modules/events/disease_outbreak.dm
  code/modules/jobs/job_types/virologist.dm
  tgstation.dme
Labels: Mapping, Removal

#89 [PORT] Free Preformance from TG
  code/__DEFINES/callbacks.dm
  code/datums/callback.dm
  code/datums/components/construction.dm
  code/datums/components/payment.dm
  code/modules/vehicles/mecha/mecha_construction_paths.dm
Labels: Port

#90 No more funny spray
  code/game/objects/items/crayons.dm
  icons/effects/96x32.dmi
Labels: Sprites

#92 [PORT] Papercode lag fix!
  code/modules/paperwork/paper.dm
  tgui/packages/tgui/interfaces/PaperSheet.tsx
  tgui/packages/tgui/package.json
  tgui/yarn.lock
Labels: UI, Port, Fix

#66 Ports LOOC and LOOC typing indicators from Orbstation
  code/__DEFINES/chat.dm
  code/__DEFINES/keybinding.dm
  code/__DEFINES/logging.dm
  code/__DEFINES/speech_channels.dm
  code/__HELPERS/logging/_logging.dm
  code/__HELPERS/logging/game.dm
  code/_globalvars/configuration.dm
  code/controllers/configuration/entries/general.dm
  code/datums/keybinding/communication.dm
  code/datums/keybinding/living.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/server.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/looc.dm
  code/modules/client/verbs/ooc.dm
  code/modules/mob/mob_defines.dm
  code/modules/tgui_input/say_modal/modal.dm
  code/modules/tgui_input/say_modal/speech.dm
  code/modules/tgui_input/say_modal/typing.dm
  icons/mob/effects/talk.dmi
  tgstation.dme
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-say/constants/index.tsx
  tgui/packages/tgui-say/styles/colors.scss
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/legacy_chat_toggles.tsx
Labels: Config Update, Sprites, UI

#93 [WOW]Fixes Boxes not scaling properly
  code/datums/storage/storage.dm
Labels: Fix

#95 [PORT] Ports big light fixture sprites from Skyrat.
  icons/obj/lighting.dmi
  icons/obj/lighting_overlay.dmi
Labels: Sprites, Port

#94 [PORT] Knock knock (Ports knocking on doors and firelocks from DD)
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  sound/effects/door_metal_knock_1.ogg
Labels: Sounds, Port

#97 [PORT] Knock knock (Attempt no.2 at porting knocking from DD)
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/modules/interaction_particle/interaction_particle.dm
  goon/LICENSE.md
  goon/README.md
  goon/dummy.dme
  goon/icons/mob/interact.dmi
  goon/sounds/door_metal_knock_1.ogg
Labels: Port, Fix

#100 [PORT] Ports 3/4 Centcom walls from Pariah
  _maps/RandomRuins/IceRuins/icemoon_surface_lust.dmm
  _maps/RandomRuins/IceRuins/icemoon_underground_mailroom.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_cube.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_gluttony.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_hierophant.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_pride.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_sloth.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_wizard.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
  _maps/RandomRuins/SpaceRuins/hellfactory.dmm
  _maps/RandomRuins/SpaceRuins/hilbertresearchfacility.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/CTF/classic.dmm
  _maps/map_files/CTF/cruiser.dmm
  _maps/map_files/CTF/fourSide.dmm
  _maps/map_files/CTF/limbo.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/Mafia/mafia_ayylmao.dmm
  _maps/map_files/Mafia/mafia_ball.dmm
  _maps/map_files/Mafia/mafia_gothic.dmm
  _maps/map_files/Mafia/mafia_lavaland.dmm
  _maps/map_files/Mafia/mafia_snow.dmm
  _maps/map_files/Mafia/mafia_spiderclan.dmm
  _maps/map_files/Mafia/mafia_syndie.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/shuttles/emergency_luxury.dmm
  _maps/templates/admin_thunderdome.dmm
  _maps/templates/heretic_sacrifice_template.dmm
  code/__DEFINES/icon_smoothing.dm
  code/__HELPERS/icon_smoothing.dm
  code/datums/materials/basemats.dm
  code/game/turfs/closed/_closed.dm
  code/game/turfs/closed/wall/mineral_walls.dm
Labels: Mapping, Port

#59 Bumps Dependencies Again
  dependencies.sh
Labels: Unit Tests

#102 [PORT] Ports Logarithmic audio volume from Horizon
  code/__DEFINES/sound.dm
  code/__HELPERS/roundend.dm
  code/game/sound.dm
Labels: Port

#110 [PORT] Atmos init time improvement.
  code/__DEFINES/time.dm
  code/__DEFINES/turfs.dm
  code/controllers/subsystem/air.dm
  code/game/turfs/open/_open.dm
  code/modules/surgery/organs/autosurgeon.dm
Labels: Port, Fix

#112 [PORT] Ports Prefs Load VV option from Skyrat
  code/__DEFINES/vv.dm
  code/modules/admin/view_variables/load_prefs.dm
  code/modules/mob/mob.dm
  tgstation.dme
Labels: Port

#117 [FUCK] Fixes Transit Handlers Forcing Atoms to Harddel
  code/_compile_options.dm
  code/datums/components/transit_handler.dm
  code/datums/transit_instance.dm
  code/modules/meteors/meteors.dm
Labels: Blame Rimi, OH SHIT, Fix

#118 Fix Another Source of CI Failure
  code/game/machinery/doors/door.dm
Labels: OH SHIT, Fix

#109 Directional Air Alarm Sprites
  code/modules/atmospherics/machinery/airalarm.dm
  icons/obj/airalarm.dmi
Labels: Sprites

#123 [PORT] Fixes Guests Not Having Keybinds
  code/modules/client/preferences_savefile.dm
Labels: Port, Fix

#106 [AAAA] Make Rounds Playable Without Admin Intervention With Access
  code/__DEFINES/access.dm
  code/controllers/subsystem/id_access.dm
  code/datums/id_trim/jobs.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/displaycase.dm
  code/game/objects/structures/noticeboard.dm
  code/modules/cargo/department_order.dm
  code/modules/cargo/packs.dm
  code/modules/mapping/access_helpers.dm
  code/modules/modular_computers/file_system/programs/airestorer.dm
  code/modules/research/server.dm
Labels: Blame Rimi, Fix

#108 [WIP] Tier 4 Part Removal, Bluespace RPED > Advanced RPED, No Longer Ranged
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1/mistake_inevitable.dmm
  _maps/RandomRuins/SpaceRuins/bus.dmm
  _maps/RandomRuins/SpaceRuins/hilbertresearchfacility.dmm
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/map_files/debug/runtimestation.dmm
  code/__DEFINES/research/research_categories.dm
  code/game/machinery/_machinery.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/storage/boxes/science_boxes.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/mod/mod_types.dm
  code/modules/power/cell.dm
  code/modules/recycling/disposal/bin.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/designs/power_designs.dm
  code/modules/research/designs/stock_parts_designs.dm
  code/modules/research/stock_parts.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/vehicles/mecha/combat/gygax.dm
  code/modules/vehicles/mecha/combat/marauder.dm
  code/modules/vending/_vending.dm
Labels: Balance, Mapping, Quality of Life, Removal, Fix

#125 Fixes #116 and #111
  code/_onclick/hud/fullscreen.dm
  code/modules/buildmode/buildmode.dm
Labels: Fix

#120 [PROBABLY SHITCODE] Inspection Prefs!
  code/__DEFINES/combat.dm
  code/__DEFINES/preferences.dm
  code/__HELPERS/text.dm
  code/datums/dna.dm
  code/modules/client/client_defines.dm
  code/modules/client/preferences/_preference.dm
  code/modules/client/preferences/inspection.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/inspection_panel.dm
  code/modules/surgery/bodyparts/helpers.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/InspectionPanel.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/IndexPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/InspectionPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/data.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/inspection.tsx
Labels: UI

#99 [PORT] Synths
  code/__DEFINES/DNA.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/preferences.dm
  code/__DEFINES/synths.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/bodypart_overlays/bodypart_overlay.dm
  code/datums/bodypart_overlays/mutant_bodypart_overlay.dm
  code/datums/dna.dm
  code/modules/client/preferences/_preference.dm
  code/modules/client/preferences/hair_opacity.dm
  code/modules/client/preferences/species_features/_mutant.dm
  code/modules/client/preferences/species_features/synth.dm
  code/modules/mob/dead/new_player/synth_sprite_accessories.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/synthetic.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/surgery/bodyparts/hair.dm
  code/modules/surgery/bodyparts/parts.dm
  code/modules/surgery/bodyparts/species_parts/lizard_bodyparts.dm
  code/modules/surgery/bodyparts/synth_bodyparts.dm
  code/modules/surgery/mechanic_steps.dm
  code/modules/surgery/organs/_organ.dm
  code/modules/surgery/organs/brain_synth.dm
  code/modules/surgery/organs/ears.dm
  code/modules/surgery/organs/external/_external_organs.dm
  code/modules/surgery/organs/external/antenna.dm
  code/modules/surgery/organs/external/screen.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/power_cord.dm
  code/modules/surgery/organs/stomach/stomach_synth.dm
  code/modules/surgery/organs/tongue.dm
  code/modules/surgery/robot_brain_surgery.dm
  code/modules/surgery/robot_chassis_restoration.dm
  code/modules/surgery/robot_healing.dm
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_synthetic.png
  config/game_options.txt
  icons/mob/species/synth/human_parts_greyscale.dmi
  icons/mob/species/synth/mammal_parts_greyscale.dmi
  icons/mob/species/synth/screens.dmi
  icons/mob/species/synth/surgery.dmi
  icons/mob/species/synth/synth_antennas.dmi
  icons/mob/species/synth/synth_parts.dmi
  icons/mob/species/synth/synthliz_antennas.dmi
  icons/mob/species/synth/synthliz_parts_greyscale.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
Labels: Config Update, Feature, Sprites, UI, Port

#122 [PORT] Yeets Progtots, Makes Them Admin Only, Ports Saboteurs from SR
  code/__DEFINES/role_preferences.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/modules/antagonists/traitor/datum_saboteur.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/Uplink/index.tsx
Labels: Balance, Removal, UI, Port

#124 Removes Sec, Peacekeeper and Clown Borgs
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_defines.dm
  code/modules/mob/living/silicon/robot/robot_model.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/techweb/all_nodes.dm
  config/game_options.txt
  icons/mob/silicon/robots.dmi
Labels: Balance, Config Update, Removal, Sprites, Rimi Sanctioned

#65 TGUI Latejoin Menu! (#71531)
  code/__DEFINES/jobs.dm
  code/_onclick/hud/new_player.dm
  code/controllers/subsystem/ticker.dm
  code/datums/id_trim/_id_trim.dm
  code/datums/id_trim/jobs.dm
  code/game/machinery/newscaster/newscaster_machine.dm
  code/modules/antagonists/separatist/separatist.dm
  code/modules/interview/interview.dm
  code/modules/jobs/departments/departments.dm
  code/modules/mob/dead/new_player/latejoin_menu.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/observer/orbit.dm
  code/modules/modular_computers/file_system/programs/bounty_board.dm
  code/modules/tgui/states/new_player.dm
  code/modules/vending/_vending.dm
  tgstation.dme
  tgui/packages/common/collections.ts
  tgui/packages/common/color.js
  tgui/packages/tgui/interfaces/JobSelection.tsx
  tgui/packages/tgui/interfaces/Orbit/constants.ts
  tgui/packages/tgui/interfaces/Orbit/helpers.ts
  tgui/packages/tgui/interfaces/Orbit/index.tsx
  tgui/packages/tgui/interfaces/Orbit/types.ts
  tgui/packages/tgui/interfaces/common/JobToIcon.ts
Labels: UI
