Repository Artea-Station/Artea-Station-Server, pull requests merged in 2023-11, with the labels that each got.

#345 Bearcat Fixes, New Pathfinders Shuttle and Docking Port Markers!
  _maps/map_files/Bearcat/Bearcat.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/shuttles/pathfinders_astrum.dmm
  _maps/shuttles/pathfinders_ghetto.dmm
  code/datums/shuttles.dm
  code/game/machinery/telecomms/machines/hub.dm
  code/game/machinery/telecomms/machines/relay.dm
  code/game/objects/structures/signs/signs_maps.dm
  code/modules/mining/mine_items.dm
  code/modules/shuttle/docking_area_marker.dm
  code/modules/shuttle/emergency.dm
  code/modules/shuttle/shuttle.dm
  icons/obj/signs.dmi
  tgstation.dme
Labels: Feature, Mapping, Quality of Life, Sprites, Fix

#367 Reverse Lift Button Display Order
  tgui/packages/tgui/interfaces/ElevatorPanel.tsx
Labels: Quality of Life, UI

#343 [PORT] Fancy Announcements!
  code/__DEFINES/announcements.dm
  code/__HELPERS/priority_announce.dm
  code/controllers/subsystem/communications.dm
  code/controllers/subsystem/nightshift.dm
  code/controllers/subsystem/security_level.dm
  code/controllers/subsystem/shuttle.dm
  code/datums/components/cult_ritual_item.dm
  code/game/gamemodes/dynamic/dynamic.dm
  code/game/gamemodes/game_mode.dm
  code/modules/admin/verbs/adminevents.dm
  code/modules/admin/verbs/commandreport.dm
  code/modules/antagonists/heretic/knowledge/ash_lore.dm
  code/modules/antagonists/heretic/knowledge/blade_lore.dm
  code/modules/antagonists/heretic/knowledge/flesh_lore.dm
  code/modules/antagonists/heretic/knowledge/rust_lore.dm
  code/modules/antagonists/heretic/knowledge/void_lore.dm
  code/modules/antagonists/nukeop/equipment/nuclear_challenge.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/antagonists/space_dragon/carp_rift.dm
  code/modules/antagonists/space_dragon/space_dragon.dm
  code/modules/events/communications_blackout.dm
  code/modules/events/processor_overload.dm
  code/modules/events/scrubber_overflow.dm
  code/modules/events/shuttle_insurance.dm
  code/modules/events/shuttle_loan.dm
  code/modules/hallucination/station_message.dm
  code/modules/mob/mob_helpers.dm
  code/modules/power/singularity/narsie.dm
  code/modules/power/supermatter/supermatter_delamination/delamination_effects.dm
  code/modules/security_levels/security_level_datums.dm
  code/modules/shuttle/emergency.dm
  code/modules/spells/spell_types/shapeshift/_shapeshift.dm
  tgstation.dme
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/packages/tgui/interfaces/CommandReport.tsx
Labels: Quality of Life, UI, Port

#374 Dish Drives No Longer Broadcast Every Single Fucking Message
  code/game/machinery/dish_drive.dm
Labels: Removal

#380 Removes 2/3rds of The Astrum's Thrusters
  _maps/shuttles/pathfinders_astrum.dmm
Labels: Balance, Mapping

#379 Fix Cycling Chem Cartridge Pour Amounts Bricking Them
  code/modules/reagents/chemistry/cartridges/_cartridge.dm
Labels: Fix

#372 Fix Airlock Note Overlays, Note Removal Hints, Poster Removal Examine Hint
  code/game/machinery/doors/airlock.dm
  code/game/objects/effects/contraband.dm
  icons/obj/doors/airlocks/station/note_overlays.dmi
Labels: Quality of Life, Sprites, Fix

#368 Kitchen, Botany, Chemistry and Partial Atmospherics Machinery Resprite!
  icons/obj/atmospherics/components/unary_devices.dmi
  icons/obj/atmospherics/pipes/disposal.dmi
  icons/obj/hydroponics/equipment.dmi
  icons/obj/kitchen.dmi
  icons/obj/machines/biogenerator.dmi
  icons/obj/machines/kitchenmachines.dmi
  icons/obj/medical/chemical.dmi
  icons/obj/medical/chemical_tanks.dmi
Labels: Feature, Sprites

#373 Make Vendors Show Returns as Free
  code/modules/vending/_vending.dm
  tgui/packages/tgui/interfaces/Vending.tsx
Labels: Quality of Life, UI

#383 Fixes Bearcat's Surgical Computer Not Actually Being One
  _maps/map_files/Bearcat/Bearcat.dmm
Labels: Mapping, Fix

#384 Fix Renaming Captain's Spare ID Not Updating Text, Remove Extra Typing Sounds
  code/modules/modular_computers/file_system/programs/card.dm
Labels: Fix

#382 Fix Shuttle Viewers Having Their View Set Incrorrectly
  code/modules/overmap/shuttle_control_component.dm
Labels: Fix

#378 [PORT] Finally Fixes Grilles and Elevators Having No Step Sound
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_main.dm
  code/__DEFINES/dcs/signals/signals_turf.dm
  code/__DEFINES/footsteps.dm
  code/datums/elements/footstep.dm
  code/datums/elements/footstep_override.dm
  code/game/objects/structures/industrial_lift.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/recycling/conveyor.dm
Labels: Port, Fix

#371 Fix Shuttle Autocall Being Overzealous
  code/controllers/subsystem/shuttle.dm
Labels: Quality of Life, Fix

#370 Resprite Stools, Office Chairs, Comfy Chairs, Normal Chairs and Wood+Iron+Glass Tables
  code/game/objects/structures/beds_chairs/chair.dm
  icons/obj/chairs.dmi
  icons/obj/smooth_structures/glass_table.dmi
  icons/obj/smooth_structures/table.dmi
  icons/obj/smooth_structures/wood_table.dmi
Labels: Feature, Quality of Life, Sprites

#390 Remove Shift Start Auto Blue Alert + Renames Central Command to Corporate
  code/__HELPERS/names.dm
  code/game/gamemodes/dynamic/dynamic.dm
Labels: Grammar and Formatting

#376 Bodies Can No Longer Be Easily Superheated
  code/__DEFINES/atmospherics/atmos_mob_interaction.dm
  code/datums/status_effects/debuffs/fire_stacks.dm
Labels: Fix

#385 Makes Elevator Emergency Stop Non-Silent, Fix Panel Stop Button Appearance
  _maps/RandomRuins/SpaceRuins/hilbertresearchfacility.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/datums/industrial_lift/lift_controller.dm
  code/game/objects/structures/industrial_lift_structures.dm
  tools/UpdatePaths/Artea/385_remove_speaker_buttons.txt
Labels: Mapping, Quality of Life, Tools

#388 [Port] Babylon Derelict station ruin
  _maps/RandomRuins/SpaceRuins/babylon_derelict.dmm
  code/datums/ruins/space.dm
  code/game/area/areas/ruins/space.dm
  icons/area/areas_ruins.dmi
Labels: Feature, Mapping, Sprites

#408 Nukes Prisoner crime pref
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences/prisoner_crime.dm
  code/modules/jobs/job_types/prisoner.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/prisoner_crime.tsx
Labels: Removal, UI

#407 Bearcat Wall paint + Medical lathe.
  _maps/map_files/Bearcat/Bearcat.dmm
  code/modules/mapping/mapping_helpers.dm
  icons/effects/paint_helpers.dmi
Labels: Feature, Mapping, Sprites, Fix
