Repository Artea-Station/Artea-Station-Server, pull requests merged in 2023-08, with the labels that each got.

#294 Make harddel lookups exist on unit tests by default. Don't know why it isn't like this already.
  code/_compile_options.dm
Labels: Repository

#289 [PORT] Coffee maker upgrade
  code/__DEFINES/colors.dm
  code/datums/elements/dryable.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/storage/boxes/food_boxes.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/structures/signs/signs_misc.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/machinery/coffeemaker.dm
  code/modules/reagents/reagent_containers/condiment.dm
  code/modules/reagents/reagent_containers/cups/_cup.dm
  code/modules/reagents/reagent_containers/cups/bottle.dm
  code/modules/reagents/reagent_containers/cups/drinks.dm
  code/modules/research/designs/misc_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/barsigns.dmi
  icons/obj/drinks.dmi
  icons/obj/machines/coffeemaker.dmi
  icons/obj/medical/chemical.dmi
  icons/obj/reagentfillings.dmi
Labels: Feature, Sprites, Port

#295 [Port] Slightly less dumb addiction timers
  code/__DEFINES/reagents.dm
Labels: Balance

#272 Voice Prefs!
  code/__DEFINES/sound.dm
  code/datums/dna.dm
  code/modules/client/preferences/voice.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/emote.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/voice.tsx
Labels: Quality of Life, UI

#288 Red and Blue Cable Layers Now Actually Do Things
  code/__DEFINES/power.dm
  code/modules/power/apc/apc_attack.dm
  code/modules/power/apc/apc_main.dm
  code/modules/power/apc/apc_power_proc.dm
  code/modules/power/cable.dm
  code/modules/power/floodlight.dm
  code/modules/power/multiz.dm
  code/modules/power/power.dm
  code/modules/power/singularity/emitter.dm
  code/modules/power/smes.dm
  code/modules/power/terminal.dm
  code/modules/power/tesla/coil.dm
  code/modules/power/turbine/turbine.dm
Labels: Port, Fix

#296 Fixes Badges Being Broken in the README
  .github/images/README.md
  .github/images/badges/built-with-resentment.svg
  .github/images/badges/contains-technical-debt.svg
  .github/images/badges/made-in-byond.gif
  .github/images/comics/106-tech-debt-modified.png
  .github/images/comics/131-bug-free.png
  README.md
Labels: Stale, Repository
