Repository Artea-Station/Artea-Station-Server, pull requests merged in 2023-10, with the labels that each got.

#331 [Port] Nicer Chat readability tweak from DD
  code/datums/emotes.dm
  code/game/say.dm
  code/modules/mob/mob.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Quality of Life, UI

#321 Grilles Connect to Walls
  code/game/objects/structures/grille.dm
Labels: Fix

#329 Fixes Space Ruins Not All Generating
  code/controllers/subsystem/mapping.dm
Labels: Fix

#330 Makes Limbs Unashable
  code/datums/wounds/loss.dm
  code/modules/surgery/bodyparts/dismemberment.dm
Labels: Balance, Fix

#242 [RimiChem] Cartchem! [MDB IGNORE]
  _maps/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
  _maps/RandomRuins/SpaceRuins/hilbertresearchfacility.dmm
  _maps/RandomZLevels/TheBeach.dmm
  _maps/map_files/Bearcat/Bearcat.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/debug/runtimestation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/shuttles/emergency_casino.dmm
  code/__DEFINES/reagents.dm
  code/game/objects/effects/spawners/random/food_or_drink.dm
  code/game/objects/effects/spawners/random/medical.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/devices/portable_chem_mixer.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/admin/admin_verbs.dm
  code/modules/cargo/exports/food_and_drink.dm
  code/modules/cargo/packs.dm
  code/modules/reagents/chemistry/cartridges/_cartridge.dm
  code/modules/reagents/chemistry/cartridges/cargo_crates.dm
  code/modules/reagents/chemistry/cartridges/cartridge_spawn.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser_prefabs.dm
  code/modules/research/designs/machine_designs.dm
  code/modules/research/techweb/all_nodes.dm
  icons/obj/medical/chemical.dmi
  icons/obj/reagentfillings.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/ChemDispenser.js
  tools/UpdatePaths/Artea/242_cartchem_dispensers.txt
Labels: Balance, Feature, Mapping, Fresh Like Cheese, Sprites, Tools, UI

#320 Mop QoL Improvements!
  code/game/objects/items/mop.dm
Labels: Quality of Life

#338 Remove Borgs and AI From Normal Gameplay
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/__DEFINES/research/research_categories.dm
  code/game/objects/effects/spawners/random/techstorage.dm
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/research/designs/mechfabricator_designs.dm
  code/modules/research/designs/mining_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Mapping, Removal

#334 Synth Hunger Alerts!
  code/modules/surgery/organs/stomach/_stomach.dm
Labels: Quality of Life

#319 Severely Nerf Goliaths, Remove Natural Bileworms, Fix Volcanic Planet Baseturf
  code/datums/mapgen/Cavegens/LavalandGenerator.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
  code/modules/overmap/planets/planet_types/volcanic_planet.dm
Labels: Balance, Quality of Life, Fix

#340 [Bearcat] Rework Engi Lathe Room and Bar, Misc Changes
  _maps/RandomRuins/IceRuins/icemoon_surface_engioutpost.dmm
  _maps/map_files/Bearcat/Bearcat.dmm
  code/__DEFINES/economy.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/research/machinery/_production.dm
  code/modules/research/machinery/circuit_imprinter.dm
  code/modules/research/machinery/departmental_protolathe.dm
  code/modules/research/machinery/protolathe.dm
Labels: Mapping, Quality of Life

#306 [ETERNAL PAIN] Trader Overhaul, Featuring Tech Disks!
  _maps/RandomRuins/SpaceRuins/derelict_sulaco.dmm
  _maps/map_files/debug/multiz.dmm
  code/__DEFINES/overmap.dm
  code/__DEFINES/research.dm
  code/__DEFINES/trading.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/research.dm
  code/controllers/subsystem/trading.dm
  code/datums/map_config.dm
  code/game/machinery/bank_machine.dm
  code/game/machinery/computer/_computer.dm
  code/game/machinery/slotmachine.dm
  code/game/machinery/telecomms/computers/message.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/game/objects/effects/spawners/random/exotic.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/cargo/bounties/science.dm
  code/modules/mining/machine_silo.dm
  code/modules/mining/metal_density_scanner.dm
  code/modules/overmap/overmap_objects.dm
  code/modules/overmap/overmap_shuttle.dm
  code/modules/overmap/planets/planet_generator.dm
  code/modules/overmap/propulsion_engine.dm
  code/modules/overmap/shuttle_control_component.dm
  code/modules/overmap/sun_system.dm
  code/modules/research/bepis.dm
  code/modules/research/rdconsole.dm
  code/modules/research/research_disk.dm
  code/modules/research/server.dm
  code/modules/research/techweb/_techweb.dm
  code/modules/shuttle/computer.dm
  code/modules/shuttle/shuttle.dm
  code/modules/trading/_delivery_run.dm
  code/modules/trading/_sold_goods.dm
  code/modules/trading/_trade_hub.dm
  code/modules/trading/_trader.dm
  code/modules/trading/_trader_bounty.dm
  code/modules/trading/sold_goods/goods.dm
  code/modules/trading/sold_goods/science.dm
  code/modules/trading/supplies_box.dm
  code/modules/trading/trade_hub_overmap.dm
  code/modules/trading/trade_machines.dm
  code/modules/trading/traders/science.dm
  code/modules/trading/traders/weaponry.dm
  icons/obj/structures/supplies_box.dmi
  tgstation.dme
  tgui/packages/tgui/components/LabeledList.tsx
  tgui/packages/tgui/components/Stack.tsx
  tgui/packages/tgui/interfaces/MessageMonitor.tsx
  tgui/packages/tgui/interfaces/TraderConsole.tsx
  tgui/packages/tgui/styles/base.scss
  tgui/packages/tgui/styles/components/LabeledList.scss
  tgui/packages/tgui/styles/components/Stack.scss
  tgui/packages/tgui/styles/themes/crt.scss
  tgui/packages/tgui/styles/themes/crt/crt-default.scss
  tools/pull_request_hooks/tests/flakyTestPayloads/chat_client.txt
  tools/pull_request_hooks/tests/flakyTestPayloads/monkey_business.txt
  tools/pull_request_hooks/tests/flakyTestPayloads/shapeshift.txt
Labels: Balance, Feature, Mapping, Quality of Life, Refactor, Removal, Sprites, Tools, UI

#339 Update Contributor Guidelines, Sets Some Repo Rules
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/guides/RESTRICTED_PR_TOPICS.md
Labels: Repository

#342 Fix Shuttle Wallmount Rotations!
  _maps/shuttles/pathfinders_ghetto.dmm
  code/__DEFINES/directional.dm
Labels: Mapping, Fix

#341 Quirks Menu Refit!
  tgui/packages/tgfont/config.cjs
  tgui/packages/tgfont/icons/bad-touch.svg
  tgui/packages/tgfont/icons/non-binary.svg
  tgui/packages/tgfont/icons/prosthetic-full.svg
  tgui/packages/tgfont/icons/prosthetic-leg.svg
  tgui/packages/tgfont/icons/syndicate-logo.svg
  tgui/packages/tgfont/static/tgfont.css
  tgui/packages/tgfont/static/tgfont.eot
  tgui/packages/tgfont/static/tgfont.woff2
  tgui/packages/tgui/components/StyleableSection.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/QuirksPage.tsx
  tgui/packages/tgui/styles/interfaces/PreferencesMenu.scss
Labels: Quality of Life, UI

#347 Say Sounds, Fixes Gender Setting!
  code/__DEFINES/sound.dm
  code/datums/dna.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences/voice.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living_say.dm
  code/modules/subtle/subtle.dm
  sound/voice/talksounds/me_a.ogg
  sound/voice/talksounds/me_b.ogg
  sound/voice/talksounds/me_c.ogg
  sound/voice/talksounds/me_d.ogg
  sound/voice/talksounds/me_e.ogg
  sound/voice/talksounds/me_f.ogg
  sound/voice/talksounds/say_atonal.ogg
  sound/voice/talksounds/say_normal.ogg
  sound/voice/talksounds/say_oop.ogg
  sound/voice/talksounds/say_plain.ogg
  sound/voice/talksounds/say_question.ogg
  sound/voice/talksounds/say_zoop.ogg
  sound/voice/talksounds/subtle_sound.ogg
  tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/voice.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/gender.ts
Labels: Feature, UI, Sounds, Fix
