Repository Artea-Station/Artea-Station-Server, pull requests merged in 2023-07, with the labels that each got.

#257 Yeets Lavaland Mob Projectile Damage Resistances
  code/modules/mob/living/simple_animal/hostile/mining_mobs/mining_mobs.dm
Labels: Balance

#258 Makes Foam Grenades Also Pass Through Open Atmos Turfs
  code/game/objects/effects/effect_system/fluid_spread/effects_foam.dm
Labels: Balance

#254 Fixes Being Able To Knock Electrified Doors Without Shock
  code/game/machinery/doors/airlock.dm
Labels: Fix

#266 [PORT] Potted plant revival!
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/shuttles/ferry_lighthouse.dmm
  code/game/objects/items/kirbyplants.dm
  code/modules/research/designs/autolathe_designs.dm
Labels: Mapping, Quality of Life, Port

#264 [PORT] Changes the Smes sprite to the Horizon Smes
  icons/obj/power.dmi
Labels: Sprites, Port

#261 [PORT] Adds a new space ambience track and fixes space ambience cutting off.
  code/_globalvars/lists/ambience.dm
  code/game/area/areas/misc.dm
  sound/ambience/ambispace4.ogg
Labels: Sounds, Port, Fix

#237 Kilo virology removal, chem factory removal, chem storage addition
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Removal

#267 [PORT] Changes the UI of the message console and Telecomms monitor to TGUI
  code/game/machinery/telecomms/computers/message.dm
  code/game/machinery/telecomms/computers/telemonitor.dm
  tgui/packages/tgui/interfaces/MessageMonitor.tsx
  tgui/packages/tgui/interfaces/TelecommsMonitor.tsx
Labels: UI, Port

#270 Fix Changelog Compiling
  .github/workflows/compile_changelogs.yml
Labels: Continuous Integration, Repository

#271 Drops all pickaxes by one size.
  code/modules/mining/equipment/mining_tools.dm
Labels: Quality of Life

#221 [PORT] Cryopods and Ghost Spawner Announcements!
  _maps/map_files/KiloStation/KiloStation.dmm
  code/datums/records/manifest.dm
  code/datums/records/record.dm
  code/game/gamemodes/objective.dm
  code/modules/cryosleep/admin.dm
  code/modules/cryosleep/ai.dm
  code/modules/cryosleep/config.dm
  code/modules/cryosleep/cryo_console_return.dm
  code/modules/cryosleep/cryopod.dm
  code/modules/cryosleep/job.dm
  code/modules/cryosleep/mind.dm
  code/modules/cryosleep/mood.dm
  code/modules/cryosleep/readme.md
  code/modules/jobs/job_types/chaplain.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/logout.dm
  code/modules/mob_spawn/mob_spawn.dm
  icons/obj/machines/cryogenics.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/CryopodConsole.js
Labels: Mapping, Sprites, Tools, UI, Port

#251 Space Ruins Variety Pack
  _maps/RandomRuins/SpaceRuins/botanical_haven.dmm
  _maps/RandomRuins/SpaceRuins/pod_crash.dmm
  _maps/RandomRuins/SpaceRuins/space_ghost_restaurant.dmm
  _maps/RandomRuins/SpaceRuins/waystation.dmm
  code/datums/holocall.dm
  code/datums/id_trim/ruins.dm
  code/datums/ruins/space.dm
  code/game/area/areas/ruins/space.dm
  code/modules/mapfluff/ruins/spaceruin_code/waystation.dm
  code/modules/shuttle/white_ship.dm
  config/spaceruinblacklist.txt
  tgstation.dme
Labels: Config Update, Mapping, Stale

#268 [PORT] Speaking in Sign language no longer reveals your identity.
  code/game/say.dm
  code/modules/mob/living/living_say.dm
Labels: Port, Fix

#256 [PORT] Job Agechecks!
  code/__DEFINES/jobs.dm
  code/controllers/subsystem/job.dm
  code/modules/client/preferences/age.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/internal_affairs_agent.dm
  code/modules/jobs/job_types/personal_ai.dm
  code/modules/jobs/job_types/positronic_brain.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/pathfinders/pathfinder_lead_job.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/age.tsx
Labels: Quality of Life, UI, Port, Fix

#276 [PORT] Manufacturer Descriptions!
  code/__DEFINES/manufacturers.dm
  code/datums/elements/manufacturer.dm
  code/game/atoms.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/modules/overmap/propulsion_engine.dm
  code/modules/pai/card.dm
  code/modules/research/machinery/_production.dm
  code/modules/surgery/organs/brain_synth.dm
  code/modules/vehicles/mecha/working/ripley.dm
  tgstation.dme
Labels: Port

#278 Merged Vending machines
  code/modules/vending/vendmerge.dm
  tgstation.dme
Labels: Quality of Life

#283 Fix: Runtime in modsuit maint program
  code/modules/modular_computers/file_system/programs/maintenance/modsuit.dm
Labels: Fix

#286 Lobby Cam Fixes
  code/__DEFINES/layers.dm
  code/controllers/subsystem/lobby_eye_ss.dm
  code/modules/client/preferences/lobby_cam.dm
Labels: Fix

#285 Ladder Controls QOL
  code/game/objects/structures/ladders.dm
Labels: Quality of Life

#273 TGUI Overmap Shuttle Panel!
  code/modules/overmap/overmap_console.dm
  code/modules/overmap/overmap_shuttle.dm
  code/modules/overmap/shuttle_control_component.dm
  code/modules/shuttle/computer.dm
  tgui/packages/tgui/interfaces/ShuttleConsole.tsx
  tgui/packages/tgui/interfaces/ShuttleConsoleOvermap.tsx
  tgui/packages/tgui/interfaces/ShuttleOvermapControls.tsx
Labels: Quality of Life, UI

#280 Prefs UI Audit Part 3 of ???
  code/modules/client/preferences.dm
  code/modules/client/preferences/middleware/food.dm
  tgui/packages/tgui/interfaces/FoodPreferences.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/FoodPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/IndexPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/data.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/names.tsx
  tgui/packages/tgui/styles/themes/crt.scss
Labels: Quality of Life, UI

#290 Action Button Animations!
  code/_onclick/hud/action_button.dm
Labels: Quality of Life
