Repository Artea-Station/Artea-Station-Server, pull requests merged in 2023-04, with the labels that each got.

#135 Swaps the TG logo with our own
  icons/ui_icons/common/artea_32.png
  icons/ui_icons/common/tg_32.png
  interface/skin.dmf
Labels: Sprites

#134 [PORT] New Decals!
  code/game/objects/effects/decals/turfdecal/vgdecals.dm
  icons/turf/vgstation_decals.dmi
  tgstation.dme
Labels: Sprites, Port

#138 Fix Synth Antennae
  code/modules/surgery/organs/external/antenna.dm
Labels: Fix

#133 [RTM] Proper Discord-Based Whitelist
  code/__DEFINES/subsystems.dm
  code/controllers/configuration/entries/dbconfig.dm
  code/controllers/subsystem/discord.dm
  code/modules/discord/accountlink.dm
  code/modules/mob/dead/new_player/login.dm
  code/modules/mob/dead/new_player/new_player.dm
  config/config.txt
Labels: Config Update, Administration, Rimi Sanctioned

#126 New Directional Extinguisher, Fire Alarm, and Lightswitch Sprites, Plus New Non-Directional Button Sprites
  code/game/machinery/buttons.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/firealarm.dm
  code/game/machinery/lightswitch.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/structures/extinguisher.dm
  code/modules/power/lighting/light_mapping_helpers.dm
  icons/obj/lighting.dmi
  icons/obj/lighting_overlay.dmi
  icons/obj/machines/camera.dmi
  icons/obj/monitors.dmi
  icons/obj/power.dmi
  icons/obj/radio.dmi
  icons/obj/stationobjs.dmi
  icons/obj/wallmounts.dmi
Labels: Balance, Mapping, Quality of Life, Sprites, UI

#127 Matchmaking and Content Preferences, Preference Descriptions, Some Related Bugfixes
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/jobs.dm
  code/__DEFINES/preferences.dm
  code/__HELPERS/game.dm
  code/controllers/subsystem/job.dm
  code/datums/dna.dm
  code/datums/matchmaking_panel.dm
  code/game/gamemodes/objective.dm
  code/game/objects/items/robot/robot_parts.dm
  code/modules/client/preferences/content.dm
  code/modules/client/preferences/inspection.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/inspection_panel.dm
  code/modules/mob/living/silicon/robot/robot_model.dm
  code/modules/mob/mob.dm
  code/modules/mob_spawn/ghost_roles/mining_roles.dm
  code/modules/mob_spawn/mob_spawn.dm
  code/modules/tgui/states/physical.dm
  code/modules/unit_tests/preferences.dm
  tgstation.dme
  tgui/packages/tgui/components/StyleableSection.tsx
  tgui/packages/tgui/interfaces/MatchmakingPanel.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/AppearancePage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/Base.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/ClothingPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/ContentPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/IndexPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/OOCPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/QuirksPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/data.ts
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/content.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/inspection.tsx
Labels: UI, Fix

#130 Antag and Event Purging: The Actually Nuclear Option
  code/__HELPERS/names.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
  code/game/machinery/computer/communications.dm
  code/modules/antagonists/disease/disease_event.dm
  code/modules/antagonists/morph/morph.dm
  code/modules/antagonists/nukeop/equipment/nuclear_authentication_disk.dm
  code/modules/antagonists/revenant/revenant_spawn_event.dm
  code/modules/antagonists/slaughter/slaughterevent.dm
  code/modules/antagonists/traitor/datum_saboteur.dm
  code/modules/antagonists/traitor/datum_traitor.dm
  code/modules/events/abductor.dm
  code/modules/events/alien_infestation.dm
  code/modules/events/blob.dm
  code/modules/events/brain_trauma.dm
  code/modules/events/creep_awakening.dm
  code/modules/events/dust.dm
  code/modules/events/fugitive_spawning.dm
  code/modules/events/market_crash.dm
  code/modules/events/meteor_wave.dm
  code/modules/events/operative.dm
  code/modules/events/portal_storm.dm
  code/modules/events/prison_break.dm
  code/modules/events/radiation_storm.dm
  code/modules/events/scrubber_clog.dm
  code/modules/events/sentience.dm
  code/modules/events/space_dragon.dm
  code/modules/events/spacevine.dm
  code/modules/events/wormholes.dm
  tgstation.dme
Labels: Balance, Quality of Life, Removal, My Opinion is Correct

#131 New Solid Wall Sprites
  icons/turf/walls/solid_wall.dmi
Labels: Sprites

#132 Replace Science Radio Defines With Pathfinder Ones, Removes Requests Consoles
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/shuttles/arrival_box.dmm
  _maps/shuttles/arrival_delta.dmm
  _maps/shuttles/arrival_kilo.dmm
  _maps/shuttles/arrival_pubby.dmm
  _maps/shuttles/emergency_monastery.dmm
  code/__DEFINES/radio.dm
  code/__DEFINES/span.dm
  code/__HELPERS/global_lists.dm
  code/controllers/subsystem/blackbox.dm
  code/game/communications.dm
  code/game/machinery/requests_console.dm
  code/game/machinery/telecomms/machines/bus.dm
  code/game/machinery/telecomms/machines/hub.dm
  code/game/machinery/telecomms/machines/message_server.dm
  code/game/machinery/telecomms/machines/receiver.dm
  code/game/machinery/telecomms/machines/server.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/granters/martial_arts/sleeping_carp.dm
  code/game/say.dm
  code/modules/admin/verbs/debug.dm
  code/modules/mining/machine_redemption.dm
  code/modules/mob/living/living_say.dm
  code/modules/mob/living/silicon/robot/robot_model.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/shuttle/arrivals.dm
  interface/stylesheet.dm
  tgstation.dme
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/packages/tgui/constants.js
  tgui/packages/tgui/interfaces/Telecomms.js
Labels: Mapping, Removal, UI, Fix

#142 [FUCK] Patches a SEVERE Security Hole
  code/modules/client/client_procs.dm
Labels: OH SHIT

#144 Swaps the NT logo for the Artea logo in TGUI
  tgui/packages/tgui/assets/bg-artea.svg
  tgui/packages/tgui/interfaces/ExodroneConsole.tsx
  tgui/packages/tgui/styles/interfaces/NuclearBomb.scss
  tgui/packages/tgui/styles/main.scss
Labels: Sprites, UI

#148 [PORT] Fixes ghost roles trying to spawn people when there /should/ be zero uses left
  code/modules/mob_spawn/mob_spawn.dm
Labels: Port, Fix

#147 [PORT] Runechat Optimization
  code/__DEFINES/text.dm
  code/controllers/subsystem/runechat.dm
  code/datums/chatmessage.dm
  code/modules/balloon_alert/balloon_alert.dm
Labels: Port

#154 Removes IceBox, Tweaks Some CI Stuff
  .github/workflows/automerge.yml
  .github/workflows/has_515_compatibility.yml
  _maps/_basemap.dm
  _maps/icebox.json
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  tools/autowiki/autowiki.js
Labels: Continuous Integration, Mapping, Removal, Tools, Repository

#156 [PORT] Adds Pixel shifting to the game!
  code/__DEFINES/keybinding.dm
  code/modules/mob/mob_movement.dm
  code/modules/pixel_shift/pixel_shift.dm
  tgstation.dme
Labels: Port

#159 Changes the Weight class for stun/tele prods
  code/game/objects/items/melee/baton.dm
Labels: Quality of Life

#157 Removes the chunky fingers check from the modular console.
  code/modules/modular_computers/computers/item/computer_ui.dm
Labels: Removal

#162 GENETICS GIB HALK PLZZZ!!!!1111!!! (Hulk Removal)
  code/datums/martial/sleeping_carp.dm
  code/datums/mutations/_combined.dm
  code/datums/mutations/hulk.dm
  code/game/objects/items/devices/scanners/health_analyzer.dm
  code/game/objects/items/dna_injector.dm
  code/game/objects/items/dualsaber.dm
  code/game/objects/items/hand_items.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/game/turfs/closed/walls.dm
  code/modules/antagonists/wishgranter/wishgranter.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/projectile/energy/stun.dm
  code/modules/spells/spell_types/self/mutate.dm
  tgstation.dme
Labels: Removal

#140 New Floor Sprites!
  code/game/objects/items/stacks/tiles/tile_reskinning.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  icons/turf/floors.dmi
Labels: Sprites

#165 [PORT] Ports Skyrat Space heater sprite
  icons/obj/atmospherics/atmos.dmi
Labels: Sprites, Port, My Opinion is Correct

#166 [PORT] Space heaters heat up a wider area.
  code/game/machinery/spaceheater.dm
Labels: Quality of Life, Port

#169 Fix Air Sensor Harddels
  code/controllers/subsystem/air.dm
  code/game/machinery/computer/atmos_computers/_air_sensor.dm
  code/game/machinery/computer/atmos_computers/inlets.dm
  code/game/machinery/computer/atmos_computers/meters.dm
  code/game/machinery/computer/atmos_computers/outlets.dm
Labels: OH SHIT, Fix

#168 Gives shovels a much more appropriate hit sound
  code/modules/mining/equipment/mining_tools.dm
Labels: Sounds
