Repository Artea-Station/Artea-Station-Server, pull requests merged in 2023-02, with the labels that each got.

#12 Rename!
  .github/CODEOWNERS
  README.md
  config/config.txt
  config/game_options.txt
  config/motd.txt
Labels: Config Update

#19 Saves on average 10 seconds from roundstart times
  code/controllers/master.dm
Labels: Code Improvement, Quality of Life

#18 Dynamically Scaling Viewport Port Port Port of a Port AAAA
  code/__DEFINES/hud.dm
  code/__DEFINES/keybinding.dm
  code/_onclick/hud/fullscreen.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/hud/screentip.dm
  code/controllers/configuration/entries/game_options.dm
  code/datums/components/storage/storage.dm
  code/datums/keybinding/client.dm
  code/datums/view.dm
  code/modules/admin/admin_verbs.dm
  code/modules/buildmode/buttons.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences/icon_size.dm
  code/modules/client/preferences/scaling_method.dm
  code/modules/client/preferences/widescreen.dm
  code/modules/client/verbs/ooc.dm
  code/modules/client/verbs/viewport.dm
  code/modules/mob/login.dm
  config/game_options.txt
  interface/skin.dmf
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/icon_size.tsx
Labels: Accessibility, Code Improvement, Config Update, Port

#13 Shuts up Off-Station Gravgen Announcements
  code/modules/power/gravitygenerator.dm
Labels: Quality of Life

#22 Adjust Autolabeler Regex
  .github/pr_labels.yml
Labels: Repository

#24 Fixes Minimum Version, Oops
  config/config.txt
Labels: Blame Rimi, Config Update, Fix

#23 Fix Linter Failing Cause of Missed Proc Macro Conversions
  code/__DEFINES/~skyrat_defines/hud.dm
  code/datums/components/storage/storage.dm
  code/datums/mocking/client.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/icon_size.tsx
Labels: Blame Rimi, UI, Fix

#27 Fix Byond Version Check
  config/config.txt
  tgui/yarn.lock
Labels: Config Update, UI

#31 Saves on average 10 seconds from roundstart times
  code/controllers/master.dm
Labels: Code Improvement

#32 Ports Buildable Stairs
  code/controllers/subsystem/materials.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/stairs.dm
  icons/obj/stairs.dmi
Labels: Sprites

#29 Removes the payday modifier
  code/game/machinery/computer/accounting.dm
  code/modules/economy/account.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
Labels: Balance, Removal, Rimi Sanctioned

#26 [PORT] JSON Saves
  code/__DEFINES/client.dm
  code/datums/json_savefile.dm
  code/datums/mocking/client.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences/_preference.dm
  code/modules/client/preferences/migrations/body_type_migration.dm
  code/modules/client/preferences/migrations/convert_to_json_savefile.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/anonymous_themes.dm
  code/modules/unit_tests/json_savefile_importing.dm
  code/modules/unit_tests/nuke_cinematic.dm
  code/modules/unit_tests/preferences.dm
  code/modules/unit_tests/security_officer_distribution.dm
  tgstation.dme
Labels: Port

#34 [PORT] Adds sound and animation to throwing items.
  code/modules/mob/living/carbon/carbon.dm
Labels: Quality of Life, Port

#36 Fix Changelog Generation
  tools/pull_request_hooks/autoChangelog.js
  tools/pull_request_hooks/autoChangelog.test.js
  tools/pull_request_hooks/changelogConfig.js
  tools/pull_request_hooks/changelogParser.js
  tools/pull_request_hooks/changelogParser.test.js
  tools/pull_request_hooks/package.json
  tools/pull_request_hooks/removeGuideComments.js
  tools/pull_request_hooks/rerunFlakyTests.js
Labels: Blame Rimi, Tools, Fix

#25 Dynamically Scaling Viewport
  code/__DEFINES/hud.dm
  code/__DEFINES/keybinding.dm
  code/_onclick/hud/fullscreen.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/hud/screentip.dm
  code/controllers/configuration/entries/game_options.dm
  code/datums/keybinding/client.dm
  code/datums/view.dm
  code/modules/admin/admin_verbs.dm
  code/modules/buildmode/buttons.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences/icon_size.dm
  code/modules/client/preferences/scaling_method.dm
  code/modules/client/preferences/widescreen.dm
  code/modules/client/verbs/ooc.dm
  code/modules/client/verbs/viewport.dm
  code/modules/mob/login.dm
  interface/skin.dmf
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/icon_size.tsx
Labels: Config Update, UI

#37 Cameras and lights now take power from adjacent walls if placed in external areas without power
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/game/machinery/_machinery.dm
  code/game/machinery/camera/camera.dm
  code/modules/power/lighting/light.dm
Labels: Mapping

#41 Sophie's Airlock Service
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/shutters.dm
  sound/machines/airlock_close.ogg
  sound/machines/airlock_close_force.ogg
  sound/machines/airlock_open.ogg
  sound/machines/airlock_open_force.ogg
  sound/machines/blastdoor_close.ogg
  sound/machines/blastdoor_open.ogg
  sound/machines/shutters_close.ogg
  sound/machines/shutters_open.ogg
Labels: Sounds

#45 Interact Icons
  code/__DEFINES/interaction_particle.dm
  code/_onclick/click.dm
  code/_onclick/other_mobs.dm
  code/game/machinery/doors/door.dm
  code/modules/interaction_particle/interaction_particle.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living.dm
  code/modules/power/lighting/light.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  icons/mob/interact.dmi
  tgstation.dme
Labels: Sprites

#44 Reach Around~
  code/__DEFINES/flags.dm
  code/_onclick/adjacent.dm
  code/game/machinery/_machinery.dm
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Sprites

#48 remove auxlua
  .github/workflows/run_integration_tests.yml
  code/__DEFINES/admin.dm
  code/__HELPERS/auxtools.dm
  code/__HELPERS/logging/debug.dm
  code/_globalvars/logging.dm
  code/controllers/subsystem/lua.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/lua/README.md
  code/modules/admin/verbs/lua/_hooks.dm
  code/modules/admin/verbs/lua/_wrappers.dm
  code/modules/admin/verbs/lua/helpers.dm
  code/modules/admin/verbs/lua/lua_editor.dm
  code/modules/admin/verbs/lua/lua_state.dm
  config/config.txt
  config/lua.txt
  dependencies.sh
  lua/SS13.lua
  tgstation.dme
  tools/ci/install_auxlua.sh
Labels: Config Update, Continuous Integration, Tools, Repository, Rimi Sanctioned

#49 How Very Gender of You
  code/__DEFINES/DNA.dm
  code/datums/dna.dm
  code/datums/gender_neuter.dm
  code/modules/admin/create_mob.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/gender.ts
Labels: UI

#47 Ignore AI and respawn flags in server title, add discord link, remove jobs config
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/job.dm
  code/game/world.dm
  config/config.txt
  config/game_options.txt
  config/jobs.txt
Labels: Config Update, Removal

#39 Removes Various Unfunny things from the Codebase
  _maps/RandomRuins/SpaceRuins/thelizardsgas.dmm
  _maps/shuttles/emergency_bar.dmm
  _maps/shuttles/emergency_discoinferno.dmm
  _maps/shuttles/pirate_dutchman.dmm
  _maps/templates/holodeck_thunderdome1218.dmm
  code/_globalvars/phobias.dm
  code/datums/brain_damage/imaginary_friend.dm
  code/datums/brain_damage/mild.dm
  code/datums/brain_damage/special.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/crafting/tailoring.dm
  code/datums/mutations/body.dm
  code/datums/station_traits/negative_traits.dm
  code/datums/status_effects/debuffs/speech_debuffs.dm
  code/game/machinery/computer/arcade/arcade.dm
  code/game/objects/effects/spawners/random/clothing.dm
  code/game/objects/effects/spawners/random/contraband.dm
  code/game/objects/effects/spawners/random/food_or_drink.dm
  code/game/objects/effects/spawners/random/structure.dm
  code/game/objects/effects/spawners/random/trash.dm
  code/game/objects/items/clown_items.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/dna_injector.dm
  code/game/objects/items/food/meatdish.dm
  code/game/objects/items/plushes.dm
  code/game/objects/items/weaponry.dm
  code/game/objects/structures/billboard.dm
  code/modules/cargo/bounties/medical.dm
  code/modules/cargo/bounties/reagent.dm
  code/modules/cargo/exports/gear.dm
  code/modules/clothing/head/hat.dm
  code/modules/clothing/head/religious.dm
  code/modules/clothing/shoes/cowboy.dm
  code/modules/food_and_drinks/recipes/drinks/drinks_alcoholic.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_drink.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/hydroponics/grown/cannabis.dm
  code/modules/mining/abandoned_crates.dm
  code/modules/mob/living/living_say.dm
  code/modules/pai/defense.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/reagent_containers/cups/glassbottle.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/vending/wardrobes.dm
  icons/obj/toys/plushes.dmi
  strings/traumas.json
Labels: Mapping, Sprites, Rimi Sanctioned

#52 remove skyrat edits, remove asimov config
  config/game_options.txt
  tools/build/build.js
Labels: Config Update, Tools

#54 [Paperwork] adds Internal affairs agents from paradise.
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/jobs.dm
  code/datums/id_trim/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/jobs/job_types/internal_affairs_agent.dm
  code/modules/modular_computers/computers/item/role_tablet_presets.dm
  icons/mob/huds/hud.dmi
  icons/mob/landmarks.dmi
  tgstation.dme
Labels: Sprites

#57 [PORT] Ports floor sprites from Skyrat
  icons/turf/floors.dmi
Labels: Sprites, Port
