Repository Artea-Station/Artea-Station-Server, pull requests merged in 2023-06, with the labels that each got.

#206 Fix Griddle Steam Not Disappearing On Being Turned Off
  code/__DEFINES/dcs/signals/signals_food.dm
  code/datums/components/grillable.dm
  code/modules/food_and_drinks/machinery/griddle.dm
Labels: Stale, Fix

#223 Trims Down ERP-Related Prefs, Fixes Some Inspection Bugs
  code/datums/matchmaking_panel.dm
  code/modules/client/preferences/content.dm
  code/modules/mob/living/carbon/human/inspection_panel.dm
  tgui/packages/tgui/interfaces/InspectionPanel.tsx
  tgui/packages/tgui/interfaces/MatchmakingPanel.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/content.tsx
Labels: Removal, UI, Fix

#224 [PORT] Ports CRT TGUI from CM
  tgui/packages/tgui/index.js
  tgui/packages/tgui/styles/components/Input.scss
  tgui/packages/tgui/styles/themes/crt.scss
  tgui/packages/tgui/styles/themes/crt/crt-blue.scss
  tgui/packages/tgui/styles/themes/crt/crt-green.scss
  tgui/packages/tgui/styles/themes/crt/crt-yellow.scss
Labels: UI, Port

#207 Ports Skyrat Tool Sprites
  icons/mob/inhands/equipment/tools_lefthand.dmi
  icons/mob/inhands/equipment/tools_righthand.dmi
  icons/obj/janitor.dmi
  icons/obj/tools.dmi
Labels: Sprites

#205 Makes Lighting Respect Perspective Walls!
  code/__HELPERS/icon_smoothing.dm
  code/game/turfs/closed/walls.dm
  code/game/turfs/turf.dm
  code/modules/lighting/lighting_object.dm
  icons/effects/lighting_object.dmi
Labels: Quality of Life, Sprites

#220 [PORT] Crew Transfers!
  code/controllers/configuration/entries/crew_transfer.dm
  code/controllers/subsystem/autotransfer.dm
  code/controllers/subsystem/shuttle.dm
  code/datums/votes/_vote_datum.dm
  code/datums/votes/crew_transfer.dm
  code/modules/shuttle/emergency.dm
  config/categories/crew_transfer.txt
  config/config.txt
  tgstation.dme
Labels: Config Update, Quality of Life, Port

#228 [PORT] Grilles will no longer shock you when they're placed on a floor tile with a wire below it.
  code/game/objects/structures/grille.dm
Labels: Port, Fix

#227 [PORT] Fixes floating point inaccuracies in numeric preferences
  code/__HELPERS/sanitize_values.dm
  code/modules/client/preferences/_preference.dm
Labels: Port, Fix

#234 Removes Roundstart MODsuits and replaces them with Hardsuits on Kilostation.
  _maps/map_files/KiloStation/KiloStation.dmm
  code/game/machinery/suit_storage_unit.dm
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Balance, Mapping, Removal

#229 Fixes A Wall Lighting Overlay
  icons/effects/lighting_object.dmi
Labels: Sprites, Fix

#230 Fixes Floor Tile Stacks
  code/game/objects/items/stacks/tiles/tile_types.dm
  icons/obj/tiles.dmi
Labels: Blame Rimi, Sprites, Fix

#235 Ghosts No Longer Go Beep Boop
  code/game/machinery/_machinery.dm
Labels: Fix

#233 TGUI Say v1.2!
  code/modules/tgui_input/say_modal/modal.dm
  interface/skin.dmf
  tgui/packages/common/keys.ts
  tgui/packages/common/timer.ts
  tgui/packages/tgui-say/ChannelIterator.ts
  tgui/packages/tgui-say/ChatHistory.test.ts
  tgui/packages/tgui-say/ChatHistory.ts
  tgui/packages/tgui-say/TguiSay.tsx
  tgui/packages/tgui-say/components/dragzone.tsx
  tgui/packages/tgui-say/constants.ts
  tgui/packages/tgui-say/constants/index.tsx
  tgui/packages/tgui-say/fonts/VT323-Regular.ttf
  tgui/packages/tgui-say/handlers/arrowKeys.tsx
  tgui/packages/tgui-say/handlers/backspaceDelete.tsx
  tgui/packages/tgui-say/handlers/click.tsx
  tgui/packages/tgui-say/handlers/componentMount.tsx
  tgui/packages/tgui-say/handlers/componentUpdate.tsx
  tgui/packages/tgui-say/handlers/enter.tsx
  tgui/packages/tgui-say/handlers/escape.tsx
  tgui/packages/tgui-say/handlers/force.tsx
  tgui/packages/tgui-say/handlers/incrementChannel.tsx
  tgui/packages/tgui-say/handlers/index.tsx
  tgui/packages/tgui-say/handlers/input.tsx
  tgui/packages/tgui-say/handlers/keyDown.tsx
  tgui/packages/tgui-say/handlers/radioPrefix.tsx
  tgui/packages/tgui-say/handlers/reset.tsx
  tgui/packages/tgui-say/handlers/setSize.tsx
  tgui/packages/tgui-say/handlers/viewHistory.tsx
  tgui/packages/tgui-say/helpers.ts
  tgui/packages/tgui-say/helpers/index.tsx
  tgui/packages/tgui-say/index.tsx
  tgui/packages/tgui-say/interfaces/TguiSay.tsx
  tgui/packages/tgui-say/package.json
  tgui/packages/tgui-say/styles/button.scss
  tgui/packages/tgui-say/styles/colors.scss
  tgui/packages/tgui-say/styles/content.scss
  tgui/packages/tgui-say/styles/dragzone.scss
  tgui/packages/tgui-say/styles/main.scss
  tgui/packages/tgui-say/styles/modal.scss
  tgui/packages/tgui-say/styles/textarea.scss
  tgui/packages/tgui-say/styles/window.scss
  tgui/packages/tgui-say/timers.ts
  tgui/packages/tgui-say/types/index.tsx
  tgui/yarn.lock
Labels: Quality of Life, UI

#239 Pathfinders mapping tweaks (Check PR description)
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/shuttles/pathfinders_ghetto.dmm
Labels: Mapping, Removal

#241 Adds the *snap emote to the game!
  code/modules/mob/living/emote.dm
  sound/misc/fingersnap1.ogg
  sound/misc/fingersnap2.ogg
Labels: Sounds

#243 Fix Pathfinder Shuttle Being Unable To Dock At Station
  _maps/map_files/KiloStation/KiloStation.dmm
Labels: Mapping, Fix

#249 Yeets the ForgottenShip Ruin
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
  code/datums/ruins/space.dm
  code/modules/mapfluff/ruins/spaceruin_code/forgottenship.dm
  code/modules/mob_spawn/ghost_roles/unused_roles.dm
  code/modules/vending/medical.dm
  tgstation.dme
Labels: Mapping, Removal, Stale

#250 Pathfinder Lead is Now Part of CoC, CoC Priority Tweaks
  code/controllers/subsystem/job.dm
Labels: Balance, Stale, Fix

#252 Pathfinders Now Show In Job Preferences
  tgui/packages/tgui/interfaces/PreferencesMenu/JobsPage.tsx
  tgui/packages/tgui/styles/interfaces/PreferencesMenu.scss
Labels: Stale, UI, Fix

#255 Status Tab Player Count
  code/controllers/subsystem/statpanel.dm
Labels: Quality of Life

#253 [PORT] Day/Night Cycle From Horizon and Fixes Planetary Lighting!
  code/__DEFINES/layers.dm
  code/controllers/subsystem/day_night.dm
  code/controllers/subsystem/mapping.dm
  code/datums/day_night_controller.dm
  code/datums/map_config.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_controller.dm
  code/game/area/area_day_night.dm
  code/game/area/areas.dm
  code/game/area/areas/ruins/space.dm
  code/modules/lighting/lighting_object.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/map_content/icebox_define.dm
  code/modules/overmap/planets/planet_templates.dm
  code/modules/overmap/planets/planet_types/chlorine_planet.dm
  code/modules/overmap/planets/planet_types/shrouded_planet.dm
  code/modules/overmap/planets/planet_types/volcanic_planet.dm
  code/modules/overmap/planets/planetary_objects.dm
  code/modules/shuttle/on_move.dm
  icons/effects/daynight_blend.dmi
  tgstation.dme
Labels: Sprites, Port, Fix
