Repository Artea-Station/Artea-Station-Server, pull requests merged in 2024-05, with the labels that each got.

#567 [Port] Maintenance vent soulening
  code/game/objects/effects/overlays.dm
  code/game/objects/effects/particles/smoke.dm
  code/game/objects/structures/maintenance.dm
Labels: Feature, Stale

#562 ALV Belryth [MDB IGNORE][IDB IGNORE]
  _maps/alv_belryth.json
  _maps/map_files/ALV Belryth/ALV Belryth.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/shuttles/cargo_belryth.dmm
  _maps/shuttles/pathfinders_hermes.dmm
  code/datums/shuttles.dm
  code/game/area/areas/overmap_shuttles.dm
  code/game/area/areas/station.dm
  code/game/turfs/open/floor/iron_floor.dm
  code/game/turfs/open/floor/plating/misc_plating.dm
  code/modules/map_content/alv_belryth_define.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/mining/mine_items.dm
  code/modules/overmap/overmap_shuttle.dm
  config/maps.txt
  icons/area/areas_station.dmi
  icons/effects/paint_helpers.dmi
  tgstation.dme
Labels: Config Update, Feature, Mapping, Fresh Like Cheese, Sprites

#571 [Port] Fixes prs from TG
  code/modules/client/client_procs.dm
  code/modules/recycling/disposal/bin.dm
  code/modules/recycling/disposal/outlet.dm
Labels: Fix

#573 Make Roundend Shuttle Go Super Fast
  code/controllers/subsystem/shuttle.dm
Labels: Quality of Life

#575 Belryth hotglue oopsie pr
  _maps/map_files/ALV Belryth/ALV Belryth.dmm
Labels: Mapping, Fix

#569 Make Opening PDAs Ignore Lighting Checks
  code/game/objects/items.dm
  code/modules/mob/mob.dm
  code/modules/modular_computers/computers/item/pda.dm
Labels: Quality of Life

#580 Resprites Wall Paint Helpers
  icons/effects/paint_helpers.dmi
Labels: Sprites

#576 [PORT] Mobile defib mounts from TG (PR#83000)
  code/datums/components/crafting/recipes.dm
  code/game/machinery/defibrillator_mount.dm
  code/game/objects/items/defib.dm
  icons/obj/machines/defib_mount.dmi
Labels: Feature, Sprites, Port

#570 [Port] Morgue tray animation
  code/game/objects/structures/morgue.dm
Labels: Quality of Life

#577 [PORT] 'Makes tails stop wagging in death' from TG (PR#79511)
  code/modules/surgery/organs/external/tails.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/tail_wag.dm
Labels: Port, Fix

#582 [PORT] Three new plants, faux seaweed sheets and butter slices from TG (PRs #79484 & #76338)
  code/__DEFINES/food.dm
  code/game/objects/items/food/misc.dm
  code/modules/food_and_drinks/recipes/soup_mixtures.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_bread.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_guide.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_lizard.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_moth.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_spaghetti.dm
  code/modules/hydroponics/grown/beans.dm
  code/modules/hydroponics/grown/corn.dm
  code/modules/hydroponics/grown/sugarcane.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  icons/obj/food/food.dmi
  icons/obj/hydroponics/growing.dmi
  icons/obj/hydroponics/growing_vegetables.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: Balance, Feature, Quality of Life, Sprites, Port

#587 [PORT] Unterminated speech now ends in a period, automatically! from Bubber (PRs #628 & #852)
  code/__DEFINES/say.dm
  code/modules/mob/living/living_say.dm
Labels: Feature, Port
