Repository Artea-Station/Artea-Station-Server, pull requests merged in 2024-01, with the labels that each got.

#497 Fixes Synth Bodyparts Staying Inside Prefs Previews
  code/modules/surgery/bodyparts/robot_bodyparts.dm
Labels: Fix

#517 Fix Stray Supply Pods
  code/modules/cargo/packs/_packs.dm
  code/modules/events/stray_cargo.dm
Labels: Fix

#516 Fix Deliveries Not Being Completable
  code/modules/trading/delivery_runs/_delivery_run.dm
Labels: Fix

#515 Fixes Mounted Holomaps, Actually Places Them In Bearcat
  _maps/map_files/Bearcat/Bearcat.dmm
  code/modules/holomap/holomap.dm
  code/modules/holomap/holomap_datum.dm
Labels: Mapping, Fix

#513 [PORT] Literally Free Performance
  code/datums/proximity_monitor/fields/projectile_dampener.dm
  code/game/machinery/camera/motion.dm
  code/game/machinery/droneDispenser.dm
  code/game/machinery/sleepers.dm
  code/game/objects/items/devices/scanners/t_scanner.dm
  code/game/objects/items/dualsaber.dm
  code/game/objects/items/flamethrower.dm
  code/game/objects/items/food/misc.dm
  code/modules/antagonists/wizard/equipment/artefact.dm
  code/modules/assembly/health.dm
  code/modules/events/pirates.dm
  code/modules/mining/lavaland/megafauna_loot.dm
  code/modules/modular_computers/file_system/programs/radar.dm
  code/modules/power/generator.dm
  code/modules/reagents/chemistry/machinery/smoke_machine.dm
  code/modules/research/xenobiology/crossbreeding/stabilized.dm
Labels: Port

#522 [PORT] Makes ByondUI Mounting Much Less Laggy
  tgui/packages/tgui/components/ByondUi.js
Labels: UI, Port

#524 [PORT] Autoconnect Canister Ports, Make Bearcat Fuel Lines Actually Work
  _maps/map_files/Bearcat/Bearcat.dmm
  code/modules/atmospherics/machinery/components/unary_devices/portables_connector.dm
Labels: Mapping, Quality of Life, Port, Fix

#525 [PORT] TGUI Colour Picker From Bee
  code/datums/browser.dm
  code/datums/components/palette.dm
  code/game/objects/items.dm
  code/game/objects/items/RCD.dm
  code/game/objects/items/dyekit.dm
  code/game/objects/items/paint.dm
  code/game/objects/items/stacks/wrap.dm
  code/game/objects/structures/dresser.dm
  code/game/objects/structures/maintenance.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/watercloset.dm
  code/modules/admin/greyscale_modify_menu.dm
  code/modules/admin/view_variables/filterrific.dm
  code/modules/admin/view_variables/get_variables.dm
  code/modules/art/paintings.dm
  code/modules/client/preferences.dm
  code/modules/client/verbs/ooc.dm
  code/modules/clothing/head/wig.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
  code/modules/mod/modules/modules_general.dm
  code/modules/modular_computers/computers/item/computer_ui.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/research/xenobiology/crossbreeding/_clothing.dm
  code/modules/research/xenobiology/crossbreeding/prismatic.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/tgui_input/color.dm
  tgstation.dme
  tgui/packages/common/color.js
  tgui/packages/common/color.ts
  tgui/packages/tgui/components/Interactive.tsx
  tgui/packages/tgui/components/Pointer.tsx
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/ColorPickerModal.tsx
  tgui/packages/tgui/styles/interfaces/ColorPicker.scss
  tgui/packages/tgui/styles/main.scss
Labels: Quality of Life, UI, Port

#532 Makes -DCOMPILE_MAPS Actually Compile All Maps
  BUILD_ALL_MAPS.cmd
  _maps/_basemap.dm
  tools/build/build.js
Labels: Mapping, Tools

#528 Fixes a 40 Second Lagspike During Init
  code/modules/client/preferences/assets.dm
Labels: Fix

#520 [Port] More cool visuals for ballistics
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/particles.dm
  code/controllers/subsystem/explosions.dm
  code/datums/elements/debris.dm
  code/game/atoms.dm
  code/game/objects/effects/temporary_visuals/explosions.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/objs.dm
  code/game/turfs/closed/_closed.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  icons/effects/64x64.dmi
  icons/effects/96x157.dmi
  icons/effects/96x96.dmi
  icons/effects/particles/generic.dmi
  tgstation.dme
Labels: Feature, Quality of Life, Sprites

#535 Synth Damage Balance Changes
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/synthetic.dm
Labels: Balance

#534 Disables Pathfinders, Disables Their Shuttle, Adds a Project Room
  _maps/map_files/Bearcat/Bearcat.dmm
  code/__DEFINES/jobs.dm
  code/modules/jobs/job_types/ai.dm
  code/modules/jobs/job_types/cyborg.dm
  code/modules/mapping/map_specific_code/bearcat/bearcat_jobs.dm
  code/modules/pathfinders/pathfinder_job.dm
Labels: Feature, Mapping, Quality of Life, Removal

#539 Fixes a Hole in the Firing Range Roof
  _maps/map_files/Bearcat/Bearcat.dmm
Labels: Mapping, Fix

#511 [Port] Examining things will now put a message in the chat.
  code/__DEFINES/span.dm
  code/modules/mob/mob.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Feature, UI, Test Merge First

#510 [PORT] movement tweaks from DD
  code/__DEFINES/combat.dm
  code/modules/mob/mob_movement.dm
  code/modules/mod/mod_ai.dm
Labels: Balance, Port, Test Merge First

#333 [PORT] Extreme Pressures Damage Buffening
  code/__DEFINES/atmospherics/atmos_mob_interaction.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/life.dm
Labels: Balance, Fresh Like Cheese, Port, Test Merge First
