Repository Artea-Station/Artea-Station-Server, pull requests merged in 2024-06, with the labels that each got.

#593 [PORT] 'Micros bucketJoin with operator"" ' from TG (PR#79949)
  code/controllers/subsystem/timer.dm
Labels: Port

#592 [PORT] 'Adds some extra flags and args to electrocute_act' from TG (PR#78374)
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Port

#586 [PORT] Adds an app for tracking vendor stock from TG (#81582)
  code/modules/modular_computers/computers/item/disks/role_disks.dm
  code/modules/modular_computers/computers/item/role_tablet_presets.dm
  code/modules/modular_computers/file_system/programs/restock_tracker.dm
  code/modules/vending/_vending.dm
  icons/obj/modular_console.dmi
  icons/obj/modular_laptop.dmi
  icons/obj/modular_pda.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/NtosRestock.tsx
  tgui/packages/tgui/interfaces/RestockTracker.tsx
Labels: Feature, Sprites, UI, Port

#588 [PORT] 'Mobs will not path into dangerous turfs.' from TG (PR#79428)
  code/_globalvars/lists/mobs.dm
  code/datums/ai/idle_behaviors/idle_random_walk.dm
  code/datums/ai/movement/ai_movement_basic_avoidance.dm
  code/datums/ai/movement/ai_movement_dumb.dm
  code/game/turfs/open/chasm.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/space/space.dm
  code/game/turfs/turf.dm
Labels: Port, Fix

#579 [PORT] Lightswitch context and deconstruction from TG (PR#79416)
  code/game/machinery/lightswitch.dm
Labels: Quality of Life, Port

#594 Belryth shuttering and mini fixes.
  _maps/map_files/ALV Belryth/ALV Belryth.dmm
Labels: Feature, Mapping, Fix

#591 Maint lights dimmening
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/items/devices/flashlight.dm
  code/modules/power/lighting/light.dm
  code/modules/power/lighting/light_mapping_helpers.dm
Labels: Balance
