Repository Artea-Station/Artea-Station-Server, pull requests merged in 2024-04, with the labels that each got.

#566 Progress bar re-sprite
  code/datums/progressbar.dm
  icons/effects/progessbar.dmi
Labels: Feature, Sprites

#559 Chem Dispensers Are No Longer Powersinks
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Stale, Fix

#561 Ghost Z Movement QoL
  code/__DEFINES/hud.dm
  code/_onclick/hud/ghost.dm
  code/modules/mob/dead/observer/observer_movement.dm
  code/modules/mob/mob_movement.dm
  icons/hud/screen_ghost.dmi
Labels: Quality of Life, Sprites
